// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cron.proto

package cronv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CronRetryConfig defines retry configuration for cron jobs.
type CronRetryConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxRetries    int32                  `protobuf:"varint,1,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Intervals     []int32                `protobuf:"varint,2,rep,packed,name=intervals,proto3" json:"intervals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronRetryConfig) Reset() {
	*x = CronRetryConfig{}
	mi := &file_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronRetryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronRetryConfig) ProtoMessage() {}

func (x *CronRetryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronRetryConfig.ProtoReflect.Descriptor instead.
func (*CronRetryConfig) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{0}
}

func (x *CronRetryConfig) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *CronRetryConfig) GetIntervals() []int32 {
	if x != nil {
		return x.Intervals
	}
	return nil
}

// CronNotificationConfig defines notification settings for cron jobs.
type CronNotificationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnFailure     bool                   `protobuf:"varint,1,opt,name=on_failure,json=onFailure,proto3" json:"on_failure,omitempty"`
	OnSuccess     bool                   `protobuf:"varint,2,opt,name=on_success,json=onSuccess,proto3" json:"on_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronNotificationConfig) Reset() {
	*x = CronNotificationConfig{}
	mi := &file_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronNotificationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronNotificationConfig) ProtoMessage() {}

func (x *CronNotificationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronNotificationConfig.ProtoReflect.Descriptor instead.
func (*CronNotificationConfig) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{1}
}

func (x *CronNotificationConfig) GetOnFailure() bool {
	if x != nil {
		return x.OnFailure
	}
	return false
}

func (x *CronNotificationConfig) GetOnSuccess() bool {
	if x != nil {
		return x.OnSuccess
	}
	return false
}

// CronJob represents a full cron job.
type CronJob struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Id                 string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Schedule           string                  `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	ScheduleCron       string                  `protobuf:"bytes,4,opt,name=schedule_cron,json=scheduleCron,proto3" json:"schedule_cron,omitempty"`
	Command            string                  `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	WorkingDir         string                  `protobuf:"bytes,6,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	TimeoutSeconds     int32                   `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	IsEnabled          bool                    `protobuf:"varint,8,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	RetryConfig        *CronRetryConfig        `protobuf:"bytes,9,opt,name=retry_config,json=retryConfig,proto3" json:"retry_config,omitempty"`
	NotificationConfig *CronNotificationConfig `protobuf:"bytes,10,opt,name=notification_config,json=notificationConfig,proto3" json:"notification_config,omitempty"`
	Environment        map[string]string       `protobuf:"bytes,11,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags               []string                `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	LastRunAt          *timestamppb.Timestamp  `protobuf:"bytes,13,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`
	NextRunAt          *timestamppb.Timestamp  `protobuf:"bytes,14,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	CreatedAt          *timestamppb.Timestamp  `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp  `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CronJob) Reset() {
	*x = CronJob{}
	mi := &file_cron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJob) ProtoMessage() {}

func (x *CronJob) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJob.ProtoReflect.Descriptor instead.
func (*CronJob) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{2}
}

func (x *CronJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CronJob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CronJob) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CronJob) GetScheduleCron() string {
	if x != nil {
		return x.ScheduleCron
	}
	return ""
}

func (x *CronJob) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CronJob) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CronJob) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CronJob) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *CronJob) GetRetryConfig() *CronRetryConfig {
	if x != nil {
		return x.RetryConfig
	}
	return nil
}

func (x *CronJob) GetNotificationConfig() *CronNotificationConfig {
	if x != nil {
		return x.NotificationConfig
	}
	return nil
}

func (x *CronJob) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *CronJob) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CronJob) GetLastRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunAt
	}
	return nil
}

func (x *CronJob) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *CronJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CronJob) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CronExecution represents a single execution of a cron job.
type CronExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	HasExitCode   bool                   `protobuf:"varint,5,opt,name=has_exit_code,json=hasExitCode,proto3" json:"has_exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs    int32                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	HasDurationMs bool                   `protobuf:"varint,9,opt,name=has_duration_ms,json=hasDurationMs,proto3" json:"has_duration_ms,omitempty"`
	RetryCount    int32                  `protobuf:"varint,10,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	TriggeredBy   string                 `protobuf:"bytes,11,opt,name=triggered_by,json=triggeredBy,proto3" json:"triggered_by,omitempty"`
	HostName      string                 `protobuf:"bytes,12,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronExecution) Reset() {
	*x = CronExecution{}
	mi := &file_cron_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronExecution) ProtoMessage() {}

func (x *CronExecution) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronExecution.ProtoReflect.Descriptor instead.
func (*CronExecution) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{3}
}

func (x *CronExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CronExecution) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CronExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CronExecution) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CronExecution) GetHasExitCode() bool {
	if x != nil {
		return x.HasExitCode
	}
	return false
}

func (x *CronExecution) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CronExecution) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CronExecution) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CronExecution) GetHasDurationMs() bool {
	if x != nil {
		return x.HasDurationMs
	}
	return false
}

func (x *CronExecution) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *CronExecution) GetTriggeredBy() string {
	if x != nil {
		return x.TriggeredBy
	}
	return ""
}

func (x *CronExecution) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *CronExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *CronExecution) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// GetPendingExecutionsRequest requests pending executions for the authenticated user.
type GetPendingExecutionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API key for authentication
	ApiKey        string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingExecutionsRequest) Reset() {
	*x = GetPendingExecutionsRequest{}
	mi := &file_cron_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingExecutionsRequest) ProtoMessage() {}

func (x *GetPendingExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingExecutionsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{4}
}

func (x *GetPendingExecutionsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// PendingExecution represents a single pending execution to be picked up.
type PendingExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobName       string                 `protobuf:"bytes,3,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	RetryCount    int32                  `protobuf:"varint,4,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	TriggeredBy   string                 `protobuf:"bytes,5,opt,name=triggered_by,json=triggeredBy,proto3" json:"triggered_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingExecution) Reset() {
	*x = PendingExecution{}
	mi := &file_cron_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingExecution) ProtoMessage() {}

func (x *PendingExecution) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingExecution.ProtoReflect.Descriptor instead.
func (*PendingExecution) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{5}
}

func (x *PendingExecution) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *PendingExecution) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PendingExecution) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *PendingExecution) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *PendingExecution) GetTriggeredBy() string {
	if x != nil {
		return x.TriggeredBy
	}
	return ""
}

func (x *PendingExecution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetPendingExecutionsResponse returns the list of pending executions.
type GetPendingExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*PendingExecution    `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingExecutionsResponse) Reset() {
	*x = GetPendingExecutionsResponse{}
	mi := &file_cron_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingExecutionsResponse) ProtoMessage() {}

func (x *GetPendingExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingExecutionsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{6}
}

func (x *GetPendingExecutionsResponse) GetExecutions() []*PendingExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

// ClaimExecutionRequest marks an execution as being processed by a CLI agent.
type ClaimExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	HostName      string                 `protobuf:"bytes,3,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimExecutionRequest) Reset() {
	*x = ClaimExecutionRequest{}
	mi := &file_cron_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimExecutionRequest) ProtoMessage() {}

func (x *ClaimExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimExecutionRequest.ProtoReflect.Descriptor instead.
func (*ClaimExecutionRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimExecutionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ClaimExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ClaimExecutionRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

// ClaimExecutionResponse confirms the claim.
type ClaimExecutionResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Job details needed for execution
	Command        string            `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	WorkingDir     string            `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Environment    map[string]string `protobuf:"bytes,5,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32             `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClaimExecutionResponse) Reset() {
	*x = ClaimExecutionResponse{}
	mi := &file_cron_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimExecutionResponse) ProtoMessage() {}

func (x *ClaimExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimExecutionResponse.ProtoReflect.Descriptor instead.
func (*ClaimExecutionResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimExecutionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClaimExecutionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ClaimExecutionResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ClaimExecutionResponse) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ClaimExecutionResponse) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ClaimExecutionResponse) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

// UpdateExecutionRequest updates an execution with the result.
type UpdateExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // success, failed, timeout, canceled
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,5,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,6,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs    int32                  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExecutionRequest) Reset() {
	*x = UpdateExecutionRequest{}
	mi := &file_cron_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExecutionRequest) ProtoMessage() {}

func (x *UpdateExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExecutionRequest.ProtoReflect.Descriptor instead.
func (*UpdateExecutionRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateExecutionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *UpdateExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *UpdateExecutionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateExecutionRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *UpdateExecutionRequest) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *UpdateExecutionRequest) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *UpdateExecutionRequest) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *UpdateExecutionRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

// UpdateExecutionResponse confirms the update.
type UpdateExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExecutionResponse) Reset() {
	*x = UpdateExecutionResponse{}
	mi := &file_cron_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExecutionResponse) ProtoMessage() {}

func (x *UpdateExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExecutionResponse.ProtoReflect.Descriptor instead.
func (*UpdateExecutionResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateExecutionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateExecutionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetJobCommandRequest requests command details for a job.
type GetJobCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobCommandRequest) Reset() {
	*x = GetJobCommandRequest{}
	mi := &file_cron_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobCommandRequest) ProtoMessage() {}

func (x *GetJobCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobCommandRequest.ProtoReflect.Descriptor instead.
func (*GetJobCommandRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{11}
}

func (x *GetJobCommandRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetJobCommandRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// GetJobCommandResponse returns command details.
type GetJobCommandResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Command        string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	WorkingDir     string                 `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	Environment    map[string]string      `protobuf:"bytes,3,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetJobCommandResponse) Reset() {
	*x = GetJobCommandResponse{}
	mi := &file_cron_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobCommandResponse) ProtoMessage() {}

func (x *GetJobCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobCommandResponse.ProtoReflect.Descriptor instead.
func (*GetJobCommandResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{12}
}

func (x *GetJobCommandResponse) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetJobCommandResponse) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *GetJobCommandResponse) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *GetJobCommandResponse) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ListCronJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronJobsRequest) Reset() {
	*x = ListCronJobsRequest{}
	mi := &file_cron_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronJobsRequest) ProtoMessage() {}

func (x *ListCronJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronJobsRequest.ProtoReflect.Descriptor instead.
func (*ListCronJobsRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{13}
}

func (x *ListCronJobsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ListCronJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*CronJob             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronJobsResponse) Reset() {
	*x = ListCronJobsResponse{}
	mi := &file_cron_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronJobsResponse) ProtoMessage() {}

func (x *ListCronJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronJobsResponse.ProtoReflect.Descriptor instead.
func (*ListCronJobsResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{14}
}

func (x *ListCronJobsResponse) GetJobs() []*CronJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type GetCronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCronJobRequest) Reset() {
	*x = GetCronJobRequest{}
	mi := &file_cron_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCronJobRequest) ProtoMessage() {}

func (x *GetCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCronJobRequest.ProtoReflect.Descriptor instead.
func (*GetCronJobRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{15}
}

func (x *GetCronJobRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetCronJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *CronJob               `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCronJobResponse) Reset() {
	*x = GetCronJobResponse{}
	mi := &file_cron_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCronJobResponse) ProtoMessage() {}

func (x *GetCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCronJobResponse.ProtoReflect.Descriptor instead.
func (*GetCronJobResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{16}
}

func (x *GetCronJobResponse) GetJob() *CronJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type CreateCronJobRequest struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	ApiKey             string                  `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Name               string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Schedule           string                  `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	ScheduleCron       string                  `protobuf:"bytes,4,opt,name=schedule_cron,json=scheduleCron,proto3" json:"schedule_cron,omitempty"`
	Command            string                  `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	WorkingDir         string                  `protobuf:"bytes,6,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	TimeoutSeconds     int32                   `protobuf:"varint,7,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RetryConfig        *CronRetryConfig        `protobuf:"bytes,8,opt,name=retry_config,json=retryConfig,proto3" json:"retry_config,omitempty"`
	NotificationConfig *CronNotificationConfig `protobuf:"bytes,9,opt,name=notification_config,json=notificationConfig,proto3" json:"notification_config,omitempty"`
	Environment        map[string]string       `protobuf:"bytes,10,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags               []string                `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateCronJobRequest) Reset() {
	*x = CreateCronJobRequest{}
	mi := &file_cron_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCronJobRequest) ProtoMessage() {}

func (x *CreateCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCronJobRequest.ProtoReflect.Descriptor instead.
func (*CreateCronJobRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{17}
}

func (x *CreateCronJobRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateCronJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCronJobRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CreateCronJobRequest) GetScheduleCron() string {
	if x != nil {
		return x.ScheduleCron
	}
	return ""
}

func (x *CreateCronJobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CreateCronJobRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CreateCronJobRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *CreateCronJobRequest) GetRetryConfig() *CronRetryConfig {
	if x != nil {
		return x.RetryConfig
	}
	return nil
}

func (x *CreateCronJobRequest) GetNotificationConfig() *CronNotificationConfig {
	if x != nil {
		return x.NotificationConfig
	}
	return nil
}

func (x *CreateCronJobRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *CreateCronJobRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *CronJob               `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCronJobResponse) Reset() {
	*x = CreateCronJobResponse{}
	mi := &file_cron_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCronJobResponse) ProtoMessage() {}

func (x *CreateCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCronJobResponse.ProtoReflect.Descriptor instead.
func (*CreateCronJobResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{18}
}

func (x *CreateCronJobResponse) GetJob() *CronJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type UpdateCronJobRequest struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	ApiKey             string                  `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id                 string                  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Schedule           string                  `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`
	ScheduleCron       string                  `protobuf:"bytes,5,opt,name=schedule_cron,json=scheduleCron,proto3" json:"schedule_cron,omitempty"`
	Command            string                  `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`
	WorkingDir         string                  `protobuf:"bytes,7,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	TimeoutSeconds     int32                   `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	IsEnabled          bool                    `protobuf:"varint,9,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	RetryConfig        *CronRetryConfig        `protobuf:"bytes,10,opt,name=retry_config,json=retryConfig,proto3" json:"retry_config,omitempty"`
	NotificationConfig *CronNotificationConfig `protobuf:"bytes,11,opt,name=notification_config,json=notificationConfig,proto3" json:"notification_config,omitempty"`
	Environment        map[string]string       `protobuf:"bytes,12,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags               []string                `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateCronJobRequest) Reset() {
	*x = UpdateCronJobRequest{}
	mi := &file_cron_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCronJobRequest) ProtoMessage() {}

func (x *UpdateCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCronJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateCronJobRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateCronJobRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *UpdateCronJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCronJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCronJobRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *UpdateCronJobRequest) GetScheduleCron() string {
	if x != nil {
		return x.ScheduleCron
	}
	return ""
}

func (x *UpdateCronJobRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *UpdateCronJobRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *UpdateCronJobRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *UpdateCronJobRequest) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

func (x *UpdateCronJobRequest) GetRetryConfig() *CronRetryConfig {
	if x != nil {
		return x.RetryConfig
	}
	return nil
}

func (x *UpdateCronJobRequest) GetNotificationConfig() *CronNotificationConfig {
	if x != nil {
		return x.NotificationConfig
	}
	return nil
}

func (x *UpdateCronJobRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *UpdateCronJobRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *CronJob               `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCronJobResponse) Reset() {
	*x = UpdateCronJobResponse{}
	mi := &file_cron_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCronJobResponse) ProtoMessage() {}

func (x *UpdateCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCronJobResponse.ProtoReflect.Descriptor instead.
func (*UpdateCronJobResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateCronJobResponse) GetJob() *CronJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type DeleteCronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCronJobRequest) Reset() {
	*x = DeleteCronJobRequest{}
	mi := &file_cron_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCronJobRequest) ProtoMessage() {}

func (x *DeleteCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCronJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteCronJobRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteCronJobRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DeleteCronJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCronJobResponse) Reset() {
	*x = DeleteCronJobResponse{}
	mi := &file_cron_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCronJobResponse) ProtoMessage() {}

func (x *DeleteCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCronJobResponse.ProtoReflect.Descriptor instead.
func (*DeleteCronJobResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{22}
}

type EnableCronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableCronJobRequest) Reset() {
	*x = EnableCronJobRequest{}
	mi := &file_cron_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableCronJobRequest) ProtoMessage() {}

func (x *EnableCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableCronJobRequest.ProtoReflect.Descriptor instead.
func (*EnableCronJobRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{23}
}

func (x *EnableCronJobRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *EnableCronJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EnableCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *CronJob               `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableCronJobResponse) Reset() {
	*x = EnableCronJobResponse{}
	mi := &file_cron_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableCronJobResponse) ProtoMessage() {}

func (x *EnableCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableCronJobResponse.ProtoReflect.Descriptor instead.
func (*EnableCronJobResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{24}
}

func (x *EnableCronJobResponse) GetJob() *CronJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type DisableCronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableCronJobRequest) Reset() {
	*x = DisableCronJobRequest{}
	mi := &file_cron_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableCronJobRequest) ProtoMessage() {}

func (x *DisableCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableCronJobRequest.ProtoReflect.Descriptor instead.
func (*DisableCronJobRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{25}
}

func (x *DisableCronJobRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DisableCronJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DisableCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *CronJob               `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableCronJobResponse) Reset() {
	*x = DisableCronJobResponse{}
	mi := &file_cron_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableCronJobResponse) ProtoMessage() {}

func (x *DisableCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableCronJobResponse.ProtoReflect.Descriptor instead.
func (*DisableCronJobResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{26}
}

func (x *DisableCronJobResponse) GetJob() *CronJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type RunCronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCronJobRequest) Reset() {
	*x = RunCronJobRequest{}
	mi := &file_cron_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCronJobRequest) ProtoMessage() {}

func (x *RunCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCronJobRequest.ProtoReflect.Descriptor instead.
func (*RunCronJobRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{27}
}

func (x *RunCronJobRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RunCronJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RunCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *CronExecution         `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCronJobResponse) Reset() {
	*x = RunCronJobResponse{}
	mi := &file_cron_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCronJobResponse) ProtoMessage() {}

func (x *RunCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCronJobResponse.ProtoReflect.Descriptor instead.
func (*RunCronJobResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{28}
}

func (x *RunCronJobResponse) GetExecution() *CronExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type GetNextCronRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextCronRunsRequest) Reset() {
	*x = GetNextCronRunsRequest{}
	mi := &file_cron_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextCronRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextCronRunsRequest) ProtoMessage() {}

func (x *GetNextCronRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextCronRunsRequest.ProtoReflect.Descriptor instead.
func (*GetNextCronRunsRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{29}
}

func (x *GetNextCronRunsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetNextCronRunsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetNextCronRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*CronJob             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNextCronRunsResponse) Reset() {
	*x = GetNextCronRunsResponse{}
	mi := &file_cron_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNextCronRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNextCronRunsResponse) ProtoMessage() {}

func (x *GetNextCronRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNextCronRunsResponse.ProtoReflect.Descriptor instead.
func (*GetNextCronRunsResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{30}
}

func (x *GetNextCronRunsResponse) GetJobs() []*CronJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type ListCronExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronExecutionsRequest) Reset() {
	*x = ListCronExecutionsRequest{}
	mi := &file_cron_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronExecutionsRequest) ProtoMessage() {}

func (x *ListCronExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListCronExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{31}
}

func (x *ListCronExecutionsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ListCronExecutionsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ListCronExecutionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListCronExecutionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCronExecutionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListCronExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*CronExecution       `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronExecutionsResponse) Reset() {
	*x = ListCronExecutionsResponse{}
	mi := &file_cron_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronExecutionsResponse) ProtoMessage() {}

func (x *ListCronExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListCronExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{32}
}

func (x *ListCronExecutionsResponse) GetExecutions() []*CronExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

type GetCronExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCronExecutionRequest) Reset() {
	*x = GetCronExecutionRequest{}
	mi := &file_cron_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCronExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCronExecutionRequest) ProtoMessage() {}

func (x *GetCronExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCronExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetCronExecutionRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{33}
}

func (x *GetCronExecutionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetCronExecutionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCronExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *CronExecution         `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCronExecutionResponse) Reset() {
	*x = GetCronExecutionResponse{}
	mi := &file_cron_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCronExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCronExecutionResponse) ProtoMessage() {}

func (x *GetCronExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCronExecutionResponse.ProtoReflect.Descriptor instead.
func (*GetCronExecutionResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{34}
}

func (x *GetCronExecutionResponse) GetExecution() *CronExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type RetryCronExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryCronExecutionRequest) Reset() {
	*x = RetryCronExecutionRequest{}
	mi := &file_cron_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryCronExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryCronExecutionRequest) ProtoMessage() {}

func (x *RetryCronExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryCronExecutionRequest.ProtoReflect.Descriptor instead.
func (*RetryCronExecutionRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{35}
}

func (x *RetryCronExecutionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RetryCronExecutionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetryCronExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *CronExecution         `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryCronExecutionResponse) Reset() {
	*x = RetryCronExecutionResponse{}
	mi := &file_cron_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryCronExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryCronExecutionResponse) ProtoMessage() {}

func (x *RetryCronExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryCronExecutionResponse.ProtoReflect.Descriptor instead.
func (*RetryCronExecutionResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{36}
}

func (x *RetryCronExecutionResponse) GetExecution() *CronExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type ReportCronExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ExitCode      int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	HasExitCode   bool                   `protobuf:"varint,5,opt,name=has_exit_code,json=hasExitCode,proto3" json:"has_exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,6,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,7,opt,name=stderr,proto3" json:"stderr,omitempty"`
	DurationMs    int32                  `protobuf:"varint,8,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	HasDurationMs bool                   `protobuf:"varint,9,opt,name=has_duration_ms,json=hasDurationMs,proto3" json:"has_duration_ms,omitempty"`
	RetryCount    int32                  `protobuf:"varint,10,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	TriggeredBy   string                 `protobuf:"bytes,11,opt,name=triggered_by,json=triggeredBy,proto3" json:"triggered_by,omitempty"`
	HostName      string                 `protobuf:"bytes,12,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCronExecutionRequest) Reset() {
	*x = ReportCronExecutionRequest{}
	mi := &file_cron_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCronExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCronExecutionRequest) ProtoMessage() {}

func (x *ReportCronExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCronExecutionRequest.ProtoReflect.Descriptor instead.
func (*ReportCronExecutionRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{37}
}

func (x *ReportCronExecutionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ReportCronExecutionRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ReportCronExecutionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportCronExecutionRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ReportCronExecutionRequest) GetHasExitCode() bool {
	if x != nil {
		return x.HasExitCode
	}
	return false
}

func (x *ReportCronExecutionRequest) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ReportCronExecutionRequest) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ReportCronExecutionRequest) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ReportCronExecutionRequest) GetHasDurationMs() bool {
	if x != nil {
		return x.HasDurationMs
	}
	return false
}

func (x *ReportCronExecutionRequest) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *ReportCronExecutionRequest) GetTriggeredBy() string {
	if x != nil {
		return x.TriggeredBy
	}
	return ""
}

func (x *ReportCronExecutionRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *ReportCronExecutionRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ReportCronExecutionRequest) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ReportCronExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *CronExecution         `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCronExecutionResponse) Reset() {
	*x = ReportCronExecutionResponse{}
	mi := &file_cron_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCronExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCronExecutionResponse) ProtoMessage() {}

func (x *ReportCronExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCronExecutionResponse.ProtoReflect.Descriptor instead.
func (*ReportCronExecutionResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{38}
}

func (x *ReportCronExecutionResponse) GetExecution() *CronExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

var File_cron_proto protoreflect.FileDescriptor

const file_cron_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cron.proto\x12\x11hookwatch.cron.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n" +
	"\x0fCronRetryConfig\x12\x1f\n" +
	"\vmax_retries\x18\x01 \x01(\x05R\n" +
	"maxRetries\x12\x1c\n" +
	"\tintervals\x18\x02 \x03(\x05R\tintervals\"V\n" +
	"\x16CronNotificationConfig\x12\x1d\n" +
	"\n" +
	"on_failure\x18\x01 \x01(\bR\tonFailure\x12\x1d\n" +
	"\n" +
	"on_success\x18\x02 \x01(\bR\tonSuccess\"\xa5\x06\n" +
	"\aCronJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12#\n" +
	"\rschedule_cron\x18\x04 \x01(\tR\fscheduleCron\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x06 \x01(\tR\n" +
	"workingDir\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x05R\x0etimeoutSeconds\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\b \x01(\bR\tisEnabled\x12E\n" +
	"\fretry_config\x18\t \x01(\v2\".hookwatch.cron.v1.CronRetryConfigR\vretryConfig\x12Z\n" +
	"\x13notification_config\x18\n" +
	" \x01(\v2).hookwatch.cron.v1.CronNotificationConfigR\x12notificationConfig\x12M\n" +
	"\venvironment\x18\v \x03(\v2+.hookwatch.cron.v1.CronJob.EnvironmentEntryR\venvironment\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12:\n" +
	"\vlast_run_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tlastRunAt\x12:\n" +
	"\vnext_run_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x03\n" +
	"\rCronExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\"\n" +
	"\rhas_exit_code\x18\x05 \x01(\bR\vhasExitCode\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x05R\n" +
	"durationMs\x12&\n" +
	"\x0fhas_duration_ms\x18\t \x01(\bR\rhasDurationMs\x12\x1f\n" +
	"\vretry_count\x18\n" +
	" \x01(\x05R\n" +
	"retryCount\x12!\n" +
	"\ftriggered_by\x18\v \x01(\tR\vtriggeredBy\x12\x1b\n" +
	"\thost_name\x18\f \x01(\tR\bhostName\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"6\n" +
	"\x1bGetPendingExecutionsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"\xe6\x01\n" +
	"\x10PendingExecution\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_name\x18\x03 \x01(\tR\ajobName\x12\x1f\n" +
	"\vretry_count\x18\x04 \x01(\x05R\n" +
	"retryCount\x12!\n" +
	"\ftriggered_by\x18\x05 \x01(\tR\vtriggeredBy\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"c\n" +
	"\x1cGetPendingExecutionsResponse\x12C\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2#.hookwatch.cron.v1.PendingExecutionR\n" +
	"executions\"p\n" +
	"\x15ClaimExecutionRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x1b\n" +
	"\thost_name\x18\x03 \x01(\tR\bhostName\"\xca\x02\n" +
	"\x16ClaimExecutionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12\\\n" +
	"\venvironment\x18\x05 \x03(\v2:.hookwatch.cron.v1.ClaimExecutionResponse.EnvironmentEntryR\venvironment\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x02\n" +
	"\x16UpdateExecutionRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x05 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x06 \x01(\tR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x05R\n" +
	"durationMs\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"I\n" +
	"\x17UpdateExecutionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"F\n" +
	"\x14GetJobCommandRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"\x98\x02\n" +
	"\x15GetJobCommandResponse\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12[\n" +
	"\venvironment\x18\x03 \x03(\v29.hookwatch.cron.v1.GetJobCommandResponse.EnvironmentEntryR\venvironment\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x13ListCronJobsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"F\n" +
	"\x14ListCronJobsResponse\x12.\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1a.hookwatch.cron.v1.CronJobR\x04jobs\"<\n" +
	"\x11GetCronJobRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"B\n" +
	"\x12GetCronJobResponse\x12,\n" +
	"\x03job\x18\x01 \x01(\v2\x1a.hookwatch.cron.v1.CronJobR\x03job\"\xbb\x04\n" +
	"\x14CreateCronJobRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\x12#\n" +
	"\rschedule_cron\x18\x04 \x01(\tR\fscheduleCron\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\x06 \x01(\tR\n" +
	"workingDir\x12'\n" +
	"\x0ftimeout_seconds\x18\a \x01(\x05R\x0etimeoutSeconds\x12E\n" +
	"\fretry_config\x18\b \x01(\v2\".hookwatch.cron.v1.CronRetryConfigR\vretryConfig\x12Z\n" +
	"\x13notification_config\x18\t \x01(\v2).hookwatch.cron.v1.CronNotificationConfigR\x12notificationConfig\x12Z\n" +
	"\venvironment\x18\n" +
	" \x03(\v28.hookwatch.cron.v1.CreateCronJobRequest.EnvironmentEntryR\venvironment\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x15CreateCronJobResponse\x12,\n" +
	"\x03job\x18\x01 \x01(\v2\x1a.hookwatch.cron.v1.CronJobR\x03job\"\xea\x04\n" +
	"\x14UpdateCronJobRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bschedule\x18\x04 \x01(\tR\bschedule\x12#\n" +
	"\rschedule_cron\x18\x05 \x01(\tR\fscheduleCron\x12\x18\n" +
	"\acommand\x18\x06 \x01(\tR\acommand\x12\x1f\n" +
	"\vworking_dir\x18\a \x01(\tR\n" +
	"workingDir\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\t \x01(\bR\tisEnabled\x12E\n" +
	"\fretry_config\x18\n" +
	" \x01(\v2\".hookwatch.cron.v1.CronRetryConfigR\vretryConfig\x12Z\n" +
	"\x13notification_config\x18\v \x01(\v2).hookwatch.cron.v1.CronNotificationConfigR\x12notificationConfig\x12Z\n" +
	"\venvironment\x18\f \x03(\v28.hookwatch.cron.v1.UpdateCronJobRequest.EnvironmentEntryR\venvironment\x12\x12\n" +
	"\x04tags\x18\r \x03(\tR\x04tags\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x15UpdateCronJobResponse\x12,\n" +
	"\x03job\x18\x01 \x01(\v2\x1a.hookwatch.cron.v1.CronJobR\x03job\"?\n" +
	"\x14DeleteCronJobRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x17\n" +
	"\x15DeleteCronJobResponse\"?\n" +
	"\x14EnableCronJobRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"E\n" +
	"\x15EnableCronJobResponse\x12,\n" +
	"\x03job\x18\x01 \x01(\v2\x1a.hookwatch.cron.v1.CronJobR\x03job\"@\n" +
	"\x15DisableCronJobRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"F\n" +
	"\x16DisableCronJobResponse\x12,\n" +
	"\x03job\x18\x01 \x01(\v2\x1a.hookwatch.cron.v1.CronJobR\x03job\"<\n" +
	"\x11RunCronJobRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"T\n" +
	"\x12RunCronJobResponse\x12>\n" +
	"\texecution\x18\x01 \x01(\v2 .hookwatch.cron.v1.CronExecutionR\texecution\"G\n" +
	"\x16GetNextCronRunsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"I\n" +
	"\x17GetNextCronRunsResponse\x12.\n" +
	"\x04jobs\x18\x01 \x03(\v2\x1a.hookwatch.cron.v1.CronJobR\x04jobs\"\x91\x01\n" +
	"\x19ListCronExecutionsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"^\n" +
	"\x1aListCronExecutionsResponse\x12@\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2 .hookwatch.cron.v1.CronExecutionR\n" +
	"executions\"B\n" +
	"\x17GetCronExecutionRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"Z\n" +
	"\x18GetCronExecutionResponse\x12>\n" +
	"\texecution\x18\x01 \x01(\v2 .hookwatch.cron.v1.CronExecutionR\texecution\"D\n" +
	"\x19RetryCronExecutionRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\\\n" +
	"\x1aRetryCronExecutionResponse\x12>\n" +
	"\texecution\x18\x01 \x01(\v2 .hookwatch.cron.v1.CronExecutionR\texecution\"\xf9\x03\n" +
	"\x1aReportCronExecutionRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\"\n" +
	"\rhas_exit_code\x18\x05 \x01(\bR\vhasExitCode\x12\x16\n" +
	"\x06stdout\x18\x06 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\a \x01(\tR\x06stderr\x12\x1f\n" +
	"\vduration_ms\x18\b \x01(\x05R\n" +
	"durationMs\x12&\n" +
	"\x0fhas_duration_ms\x18\t \x01(\bR\rhasDurationMs\x12\x1f\n" +
	"\vretry_count\x18\n" +
	" \x01(\x05R\n" +
	"retryCount\x12!\n" +
	"\ftriggered_by\x18\v \x01(\tR\vtriggeredBy\x12\x1b\n" +
	"\thost_name\x18\f \x01(\tR\bhostName\x129\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"]\n" +
	"\x1bReportCronExecutionResponse\x12>\n" +
	"\texecution\x18\x01 \x01(\v2 .hookwatch.cron.v1.CronExecutionR\texecution2\xfc\r\n" +
	"\vCronService\x12w\n" +
	"\x14GetPendingExecutions\x12..hookwatch.cron.v1.GetPendingExecutionsRequest\x1a/.hookwatch.cron.v1.GetPendingExecutionsResponse\x12e\n" +
	"\x0eClaimExecution\x12(.hookwatch.cron.v1.ClaimExecutionRequest\x1a).hookwatch.cron.v1.ClaimExecutionResponse\x12h\n" +
	"\x0fUpdateExecution\x12).hookwatch.cron.v1.UpdateExecutionRequest\x1a*.hookwatch.cron.v1.UpdateExecutionResponse\x12b\n" +
	"\rGetJobCommand\x12'.hookwatch.cron.v1.GetJobCommandRequest\x1a(.hookwatch.cron.v1.GetJobCommandResponse\x12_\n" +
	"\fListCronJobs\x12&.hookwatch.cron.v1.ListCronJobsRequest\x1a'.hookwatch.cron.v1.ListCronJobsResponse\x12Y\n" +
	"\n" +
	"GetCronJob\x12$.hookwatch.cron.v1.GetCronJobRequest\x1a%.hookwatch.cron.v1.GetCronJobResponse\x12b\n" +
	"\rCreateCronJob\x12'.hookwatch.cron.v1.CreateCronJobRequest\x1a(.hookwatch.cron.v1.CreateCronJobResponse\x12b\n" +
	"\rUpdateCronJob\x12'.hookwatch.cron.v1.UpdateCronJobRequest\x1a(.hookwatch.cron.v1.UpdateCronJobResponse\x12b\n" +
	"\rDeleteCronJob\x12'.hookwatch.cron.v1.DeleteCronJobRequest\x1a(.hookwatch.cron.v1.DeleteCronJobResponse\x12b\n" +
	"\rEnableCronJob\x12'.hookwatch.cron.v1.EnableCronJobRequest\x1a(.hookwatch.cron.v1.EnableCronJobResponse\x12e\n" +
	"\x0eDisableCronJob\x12(.hookwatch.cron.v1.DisableCronJobRequest\x1a).hookwatch.cron.v1.DisableCronJobResponse\x12Y\n" +
	"\n" +
	"RunCronJob\x12$.hookwatch.cron.v1.RunCronJobRequest\x1a%.hookwatch.cron.v1.RunCronJobResponse\x12h\n" +
	"\x0fGetNextCronRuns\x12).hookwatch.cron.v1.GetNextCronRunsRequest\x1a*.hookwatch.cron.v1.GetNextCronRunsResponse\x12q\n" +
	"\x12ListCronExecutions\x12,.hookwatch.cron.v1.ListCronExecutionsRequest\x1a-.hookwatch.cron.v1.ListCronExecutionsResponse\x12k\n" +
	"\x10GetCronExecution\x12*.hookwatch.cron.v1.GetCronExecutionRequest\x1a+.hookwatch.cron.v1.GetCronExecutionResponse\x12q\n" +
	"\x12RetryCronExecution\x12,.hookwatch.cron.v1.RetryCronExecutionRequest\x1a-.hookwatch.cron.v1.RetryCronExecutionResponse\x12t\n" +
	"\x13ReportCronExecution\x12-.hookwatch.cron.v1.ReportCronExecutionRequest\x1a..hookwatch.cron.v1.ReportCronExecutionResponseB/Z-github.com/hookwatch-dev/proto/cron/v1;cronv1b\x06proto3"

var (
	file_cron_proto_rawDescOnce sync.Once
	file_cron_proto_rawDescData []byte
)

func file_cron_proto_rawDescGZIP() []byte {
	file_cron_proto_rawDescOnce.Do(func() {
		file_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cron_proto_rawDesc), len(file_cron_proto_rawDesc)))
	})
	return file_cron_proto_rawDescData
}

var file_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_cron_proto_goTypes = []any{
	(*CronRetryConfig)(nil),              // 0: hookwatch.cron.v1.CronRetryConfig
	(*CronNotificationConfig)(nil),       // 1: hookwatch.cron.v1.CronNotificationConfig
	(*CronJob)(nil),                      // 2: hookwatch.cron.v1.CronJob
	(*CronExecution)(nil),                // 3: hookwatch.cron.v1.CronExecution
	(*GetPendingExecutionsRequest)(nil),  // 4: hookwatch.cron.v1.GetPendingExecutionsRequest
	(*PendingExecution)(nil),             // 5: hookwatch.cron.v1.PendingExecution
	(*GetPendingExecutionsResponse)(nil), // 6: hookwatch.cron.v1.GetPendingExecutionsResponse
	(*ClaimExecutionRequest)(nil),        // 7: hookwatch.cron.v1.ClaimExecutionRequest
	(*ClaimExecutionResponse)(nil),       // 8: hookwatch.cron.v1.ClaimExecutionResponse
	(*UpdateExecutionRequest)(nil),       // 9: hookwatch.cron.v1.UpdateExecutionRequest
	(*UpdateExecutionResponse)(nil),      // 10: hookwatch.cron.v1.UpdateExecutionResponse
	(*GetJobCommandRequest)(nil),         // 11: hookwatch.cron.v1.GetJobCommandRequest
	(*GetJobCommandResponse)(nil),        // 12: hookwatch.cron.v1.GetJobCommandResponse
	(*ListCronJobsRequest)(nil),          // 13: hookwatch.cron.v1.ListCronJobsRequest
	(*ListCronJobsResponse)(nil),         // 14: hookwatch.cron.v1.ListCronJobsResponse
	(*GetCronJobRequest)(nil),            // 15: hookwatch.cron.v1.GetCronJobRequest
	(*GetCronJobResponse)(nil),           // 16: hookwatch.cron.v1.GetCronJobResponse
	(*CreateCronJobRequest)(nil),         // 17: hookwatch.cron.v1.CreateCronJobRequest
	(*CreateCronJobResponse)(nil),        // 18: hookwatch.cron.v1.CreateCronJobResponse
	(*UpdateCronJobRequest)(nil),         // 19: hookwatch.cron.v1.UpdateCronJobRequest
	(*UpdateCronJobResponse)(nil),        // 20: hookwatch.cron.v1.UpdateCronJobResponse
	(*DeleteCronJobRequest)(nil),         // 21: hookwatch.cron.v1.DeleteCronJobRequest
	(*DeleteCronJobResponse)(nil),        // 22: hookwatch.cron.v1.DeleteCronJobResponse
	(*EnableCronJobRequest)(nil),         // 23: hookwatch.cron.v1.EnableCronJobRequest
	(*EnableCronJobResponse)(nil),        // 24: hookwatch.cron.v1.EnableCronJobResponse
	(*DisableCronJobRequest)(nil),        // 25: hookwatch.cron.v1.DisableCronJobRequest
	(*DisableCronJobResponse)(nil),       // 26: hookwatch.cron.v1.DisableCronJobResponse
	(*RunCronJobRequest)(nil),            // 27: hookwatch.cron.v1.RunCronJobRequest
	(*RunCronJobResponse)(nil),           // 28: hookwatch.cron.v1.RunCronJobResponse
	(*GetNextCronRunsRequest)(nil),       // 29: hookwatch.cron.v1.GetNextCronRunsRequest
	(*GetNextCronRunsResponse)(nil),      // 30: hookwatch.cron.v1.GetNextCronRunsResponse
	(*ListCronExecutionsRequest)(nil),    // 31: hookwatch.cron.v1.ListCronExecutionsRequest
	(*ListCronExecutionsResponse)(nil),   // 32: hookwatch.cron.v1.ListCronExecutionsResponse
	(*GetCronExecutionRequest)(nil),      // 33: hookwatch.cron.v1.GetCronExecutionRequest
	(*GetCronExecutionResponse)(nil),     // 34: hookwatch.cron.v1.GetCronExecutionResponse
	(*RetryCronExecutionRequest)(nil),    // 35: hookwatch.cron.v1.RetryCronExecutionRequest
	(*RetryCronExecutionResponse)(nil),   // 36: hookwatch.cron.v1.RetryCronExecutionResponse
	(*ReportCronExecutionRequest)(nil),   // 37: hookwatch.cron.v1.ReportCronExecutionRequest
	(*ReportCronExecutionResponse)(nil),  // 38: hookwatch.cron.v1.ReportCronExecutionResponse
	nil,                                  // 39: hookwatch.cron.v1.CronJob.EnvironmentEntry
	nil,                                  // 40: hookwatch.cron.v1.ClaimExecutionResponse.EnvironmentEntry
	nil,                                  // 41: hookwatch.cron.v1.GetJobCommandResponse.EnvironmentEntry
	nil,                                  // 42: hookwatch.cron.v1.CreateCronJobRequest.EnvironmentEntry
	nil,                                  // 43: hookwatch.cron.v1.UpdateCronJobRequest.EnvironmentEntry
	(*timestamppb.Timestamp)(nil),        // 44: google.protobuf.Timestamp
}
var file_cron_proto_depIdxs = []int32{
	0,  // 0: hookwatch.cron.v1.CronJob.retry_config:type_name -> hookwatch.cron.v1.CronRetryConfig
	1,  // 1: hookwatch.cron.v1.CronJob.notification_config:type_name -> hookwatch.cron.v1.CronNotificationConfig
	39, // 2: hookwatch.cron.v1.CronJob.environment:type_name -> hookwatch.cron.v1.CronJob.EnvironmentEntry
	44, // 3: hookwatch.cron.v1.CronJob.last_run_at:type_name -> google.protobuf.Timestamp
	44, // 4: hookwatch.cron.v1.CronJob.next_run_at:type_name -> google.protobuf.Timestamp
	44, // 5: hookwatch.cron.v1.CronJob.created_at:type_name -> google.protobuf.Timestamp
	44, // 6: hookwatch.cron.v1.CronJob.updated_at:type_name -> google.protobuf.Timestamp
	44, // 7: hookwatch.cron.v1.CronExecution.started_at:type_name -> google.protobuf.Timestamp
	44, // 8: hookwatch.cron.v1.CronExecution.completed_at:type_name -> google.protobuf.Timestamp
	44, // 9: hookwatch.cron.v1.PendingExecution.created_at:type_name -> google.protobuf.Timestamp
	5,  // 10: hookwatch.cron.v1.GetPendingExecutionsResponse.executions:type_name -> hookwatch.cron.v1.PendingExecution
	40, // 11: hookwatch.cron.v1.ClaimExecutionResponse.environment:type_name -> hookwatch.cron.v1.ClaimExecutionResponse.EnvironmentEntry
	44, // 12: hookwatch.cron.v1.UpdateExecutionRequest.completed_at:type_name -> google.protobuf.Timestamp
	41, // 13: hookwatch.cron.v1.GetJobCommandResponse.environment:type_name -> hookwatch.cron.v1.GetJobCommandResponse.EnvironmentEntry
	2,  // 14: hookwatch.cron.v1.ListCronJobsResponse.jobs:type_name -> hookwatch.cron.v1.CronJob
	2,  // 15: hookwatch.cron.v1.GetCronJobResponse.job:type_name -> hookwatch.cron.v1.CronJob
	0,  // 16: hookwatch.cron.v1.CreateCronJobRequest.retry_config:type_name -> hookwatch.cron.v1.CronRetryConfig
	1,  // 17: hookwatch.cron.v1.CreateCronJobRequest.notification_config:type_name -> hookwatch.cron.v1.CronNotificationConfig
	42, // 18: hookwatch.cron.v1.CreateCronJobRequest.environment:type_name -> hookwatch.cron.v1.CreateCronJobRequest.EnvironmentEntry
	2,  // 19: hookwatch.cron.v1.CreateCronJobResponse.job:type_name -> hookwatch.cron.v1.CronJob
	0,  // 20: hookwatch.cron.v1.UpdateCronJobRequest.retry_config:type_name -> hookwatch.cron.v1.CronRetryConfig
	1,  // 21: hookwatch.cron.v1.UpdateCronJobRequest.notification_config:type_name -> hookwatch.cron.v1.CronNotificationConfig
	43, // 22: hookwatch.cron.v1.UpdateCronJobRequest.environment:type_name -> hookwatch.cron.v1.UpdateCronJobRequest.EnvironmentEntry
	2,  // 23: hookwatch.cron.v1.UpdateCronJobResponse.job:type_name -> hookwatch.cron.v1.CronJob
	2,  // 24: hookwatch.cron.v1.EnableCronJobResponse.job:type_name -> hookwatch.cron.v1.CronJob
	2,  // 25: hookwatch.cron.v1.DisableCronJobResponse.job:type_name -> hookwatch.cron.v1.CronJob
	3,  // 26: hookwatch.cron.v1.RunCronJobResponse.execution:type_name -> hookwatch.cron.v1.CronExecution
	2,  // 27: hookwatch.cron.v1.GetNextCronRunsResponse.jobs:type_name -> hookwatch.cron.v1.CronJob
	3,  // 28: hookwatch.cron.v1.ListCronExecutionsResponse.executions:type_name -> hookwatch.cron.v1.CronExecution
	3,  // 29: hookwatch.cron.v1.GetCronExecutionResponse.execution:type_name -> hookwatch.cron.v1.CronExecution
	3,  // 30: hookwatch.cron.v1.RetryCronExecutionResponse.execution:type_name -> hookwatch.cron.v1.CronExecution
	44, // 31: hookwatch.cron.v1.ReportCronExecutionRequest.started_at:type_name -> google.protobuf.Timestamp
	44, // 32: hookwatch.cron.v1.ReportCronExecutionRequest.completed_at:type_name -> google.protobuf.Timestamp
	3,  // 33: hookwatch.cron.v1.ReportCronExecutionResponse.execution:type_name -> hookwatch.cron.v1.CronExecution
	4,  // 34: hookwatch.cron.v1.CronService.GetPendingExecutions:input_type -> hookwatch.cron.v1.GetPendingExecutionsRequest
	7,  // 35: hookwatch.cron.v1.CronService.ClaimExecution:input_type -> hookwatch.cron.v1.ClaimExecutionRequest
	9,  // 36: hookwatch.cron.v1.CronService.UpdateExecution:input_type -> hookwatch.cron.v1.UpdateExecutionRequest
	11, // 37: hookwatch.cron.v1.CronService.GetJobCommand:input_type -> hookwatch.cron.v1.GetJobCommandRequest
	13, // 38: hookwatch.cron.v1.CronService.ListCronJobs:input_type -> hookwatch.cron.v1.ListCronJobsRequest
	15, // 39: hookwatch.cron.v1.CronService.GetCronJob:input_type -> hookwatch.cron.v1.GetCronJobRequest
	17, // 40: hookwatch.cron.v1.CronService.CreateCronJob:input_type -> hookwatch.cron.v1.CreateCronJobRequest
	19, // 41: hookwatch.cron.v1.CronService.UpdateCronJob:input_type -> hookwatch.cron.v1.UpdateCronJobRequest
	21, // 42: hookwatch.cron.v1.CronService.DeleteCronJob:input_type -> hookwatch.cron.v1.DeleteCronJobRequest
	23, // 43: hookwatch.cron.v1.CronService.EnableCronJob:input_type -> hookwatch.cron.v1.EnableCronJobRequest
	25, // 44: hookwatch.cron.v1.CronService.DisableCronJob:input_type -> hookwatch.cron.v1.DisableCronJobRequest
	27, // 45: hookwatch.cron.v1.CronService.RunCronJob:input_type -> hookwatch.cron.v1.RunCronJobRequest
	29, // 46: hookwatch.cron.v1.CronService.GetNextCronRuns:input_type -> hookwatch.cron.v1.GetNextCronRunsRequest
	31, // 47: hookwatch.cron.v1.CronService.ListCronExecutions:input_type -> hookwatch.cron.v1.ListCronExecutionsRequest
	33, // 48: hookwatch.cron.v1.CronService.GetCronExecution:input_type -> hookwatch.cron.v1.GetCronExecutionRequest
	35, // 49: hookwatch.cron.v1.CronService.RetryCronExecution:input_type -> hookwatch.cron.v1.RetryCronExecutionRequest
	37, // 50: hookwatch.cron.v1.CronService.ReportCronExecution:input_type -> hookwatch.cron.v1.ReportCronExecutionRequest
	6,  // 51: hookwatch.cron.v1.CronService.GetPendingExecutions:output_type -> hookwatch.cron.v1.GetPendingExecutionsResponse
	8,  // 52: hookwatch.cron.v1.CronService.ClaimExecution:output_type -> hookwatch.cron.v1.ClaimExecutionResponse
	10, // 53: hookwatch.cron.v1.CronService.UpdateExecution:output_type -> hookwatch.cron.v1.UpdateExecutionResponse
	12, // 54: hookwatch.cron.v1.CronService.GetJobCommand:output_type -> hookwatch.cron.v1.GetJobCommandResponse
	14, // 55: hookwatch.cron.v1.CronService.ListCronJobs:output_type -> hookwatch.cron.v1.ListCronJobsResponse
	16, // 56: hookwatch.cron.v1.CronService.GetCronJob:output_type -> hookwatch.cron.v1.GetCronJobResponse
	18, // 57: hookwatch.cron.v1.CronService.CreateCronJob:output_type -> hookwatch.cron.v1.CreateCronJobResponse
	20, // 58: hookwatch.cron.v1.CronService.UpdateCronJob:output_type -> hookwatch.cron.v1.UpdateCronJobResponse
	22, // 59: hookwatch.cron.v1.CronService.DeleteCronJob:output_type -> hookwatch.cron.v1.DeleteCronJobResponse
	24, // 60: hookwatch.cron.v1.CronService.EnableCronJob:output_type -> hookwatch.cron.v1.EnableCronJobResponse
	26, // 61: hookwatch.cron.v1.CronService.DisableCronJob:output_type -> hookwatch.cron.v1.DisableCronJobResponse
	28, // 62: hookwatch.cron.v1.CronService.RunCronJob:output_type -> hookwatch.cron.v1.RunCronJobResponse
	30, // 63: hookwatch.cron.v1.CronService.GetNextCronRuns:output_type -> hookwatch.cron.v1.GetNextCronRunsResponse
	32, // 64: hookwatch.cron.v1.CronService.ListCronExecutions:output_type -> hookwatch.cron.v1.ListCronExecutionsResponse
	34, // 65: hookwatch.cron.v1.CronService.GetCronExecution:output_type -> hookwatch.cron.v1.GetCronExecutionResponse
	36, // 66: hookwatch.cron.v1.CronService.RetryCronExecution:output_type -> hookwatch.cron.v1.RetryCronExecutionResponse
	38, // 67: hookwatch.cron.v1.CronService.ReportCronExecution:output_type -> hookwatch.cron.v1.ReportCronExecutionResponse
	51, // [51:68] is the sub-list for method output_type
	34, // [34:51] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_cron_proto_init() }
func file_cron_proto_init() {
	if File_cron_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cron_proto_rawDesc), len(file_cron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cron_proto_goTypes,
		DependencyIndexes: file_cron_proto_depIdxs,
		MessageInfos:      file_cron_proto_msgTypes,
	}.Build()
	File_cron_proto = out.File
	file_cron_proto_goTypes = nil
	file_cron_proto_depIdxs = nil
}
