// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: webhook/v1/webhook.proto

package webhookv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RetryConfig defines retry behavior for webhook deliveries
type RetryConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of retry attempts
	MaxRetries int32 `protobuf:"varint,1,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	// Intervals between retries in seconds [60, 300, 1800, 7200, 86400]
	Intervals     []int32 `protobuf:"varint,2,rep,packed,name=intervals,proto3" json:"intervals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryConfig) Reset() {
	*x = RetryConfig{}
	mi := &file_webhook_v1_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryConfig) ProtoMessage() {}

func (x *RetryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_v1_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryConfig.ProtoReflect.Descriptor instead.
func (*RetryConfig) Descriptor() ([]byte, []int) {
	return file_webhook_v1_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *RetryConfig) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *RetryConfig) GetIntervals() []int32 {
	if x != nil {
		return x.Intervals
	}
	return nil
}

// GetEndpointBySlugRequest is the request to lookup an endpoint
type GetEndpointBySlugRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The endpoint slug (URL path identifier)
	Slug          string `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointBySlugRequest) Reset() {
	*x = GetEndpointBySlugRequest{}
	mi := &file_webhook_v1_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointBySlugRequest) ProtoMessage() {}

func (x *GetEndpointBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_v1_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetEndpointBySlugRequest) Descriptor() ([]byte, []int) {
	return file_webhook_v1_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *GetEndpointBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

// GetEndpointBySlugResponse contains endpoint details
type GetEndpointBySlugResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endpoint UUID
	EndpointId string `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	// Owner user UUID
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Target URL for webhook delivery
	DestinationUrl string `protobuf:"bytes,3,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	// Whether the endpoint is currently active
	IsActive bool `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Retry configuration for this endpoint
	RetryConfig   *RetryConfig `protobuf:"bytes,5,opt,name=retry_config,json=retryConfig,proto3" json:"retry_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointBySlugResponse) Reset() {
	*x = GetEndpointBySlugResponse{}
	mi := &file_webhook_v1_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointBySlugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointBySlugResponse) ProtoMessage() {}

func (x *GetEndpointBySlugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_v1_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointBySlugResponse.ProtoReflect.Descriptor instead.
func (*GetEndpointBySlugResponse) Descriptor() ([]byte, []int) {
	return file_webhook_v1_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *GetEndpointBySlugResponse) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *GetEndpointBySlugResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetEndpointBySlugResponse) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

func (x *GetEndpointBySlugResponse) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *GetEndpointBySlugResponse) GetRetryConfig() *RetryConfig {
	if x != nil {
		return x.RetryConfig
	}
	return nil
}

// CreateEventRequest contains the incoming webhook data to save
type CreateEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endpoint ID (from GetEndpointBySlug)
	EndpointId string `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	// User ID (for pub/sub notifications)
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// HTTP method (POST, PUT, etc.)
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// HTTP headers from the webhook request
	Headers map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Request body
	Body []byte `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	// Source IP address of the webhook sender
	SourceIp      string `protobuf:"bytes,6,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_webhook_v1_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_v1_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_webhook_v1_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEventRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *CreateEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateEventRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreateEventRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CreateEventRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CreateEventRequest) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

// CreateEventResponse contains the created event details
type CreateEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generated event UUID
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Event creation timestamp
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_webhook_v1_webhook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_v1_webhook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_webhook_v1_webhook_proto_rawDescGZIP(), []int{4}
}

func (x *CreateEventResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateEventResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_webhook_v1_webhook_proto protoreflect.FileDescriptor

const file_webhook_v1_webhook_proto_rawDesc = "" +
	"\n" +
	"\x18webhook/v1/webhook.proto\x12\x14hookwatch.webhook.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n" +
	"\vRetryConfig\x12\x1f\n" +
	"\vmax_retries\x18\x01 \x01(\x05R\n" +
	"maxRetries\x12\x1c\n" +
	"\tintervals\x18\x02 \x03(\x05R\tintervals\".\n" +
	"\x18GetEndpointBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\xe1\x01\n" +
	"\x19GetEndpointBySlugResponse\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0fdestination_url\x18\x03 \x01(\tR\x0edestinationUrl\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12D\n" +
	"\fretry_config\x18\x05 \x01(\v2!.hookwatch.webhook.v1.RetryConfigR\vretryConfig\"\xa4\x02\n" +
	"\x12CreateEventRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12O\n" +
	"\aheaders\x18\x04 \x03(\v25.hookwatch.webhook.v1.CreateEventRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x1b\n" +
	"\tsource_ip\x18\x06 \x01(\tR\bsourceIp\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"k\n" +
	"\x13CreateEventResponse\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xea\x01\n" +
	"\x0eWebhookService\x12t\n" +
	"\x11GetEndpointBySlug\x12..hookwatch.webhook.v1.GetEndpointBySlugRequest\x1a/.hookwatch.webhook.v1.GetEndpointBySlugResponse\x12b\n" +
	"\vCreateEvent\x12(.hookwatch.webhook.v1.CreateEventRequest\x1a).hookwatch.webhook.v1.CreateEventResponseB5Z3github.com/hookwatch-dev/proto/webhook/v1;webhookv1b\x06proto3"

var (
	file_webhook_v1_webhook_proto_rawDescOnce sync.Once
	file_webhook_v1_webhook_proto_rawDescData []byte
)

func file_webhook_v1_webhook_proto_rawDescGZIP() []byte {
	file_webhook_v1_webhook_proto_rawDescOnce.Do(func() {
		file_webhook_v1_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webhook_v1_webhook_proto_rawDesc), len(file_webhook_v1_webhook_proto_rawDesc)))
	})
	return file_webhook_v1_webhook_proto_rawDescData
}

var file_webhook_v1_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_webhook_v1_webhook_proto_goTypes = []any{
	(*RetryConfig)(nil),               // 0: hookwatch.webhook.v1.RetryConfig
	(*GetEndpointBySlugRequest)(nil),  // 1: hookwatch.webhook.v1.GetEndpointBySlugRequest
	(*GetEndpointBySlugResponse)(nil), // 2: hookwatch.webhook.v1.GetEndpointBySlugResponse
	(*CreateEventRequest)(nil),        // 3: hookwatch.webhook.v1.CreateEventRequest
	(*CreateEventResponse)(nil),       // 4: hookwatch.webhook.v1.CreateEventResponse
	nil,                               // 5: hookwatch.webhook.v1.CreateEventRequest.HeadersEntry
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
}
var file_webhook_v1_webhook_proto_depIdxs = []int32{
	0, // 0: hookwatch.webhook.v1.GetEndpointBySlugResponse.retry_config:type_name -> hookwatch.webhook.v1.RetryConfig
	5, // 1: hookwatch.webhook.v1.CreateEventRequest.headers:type_name -> hookwatch.webhook.v1.CreateEventRequest.HeadersEntry
	6, // 2: hookwatch.webhook.v1.CreateEventResponse.created_at:type_name -> google.protobuf.Timestamp
	1, // 3: hookwatch.webhook.v1.WebhookService.GetEndpointBySlug:input_type -> hookwatch.webhook.v1.GetEndpointBySlugRequest
	3, // 4: hookwatch.webhook.v1.WebhookService.CreateEvent:input_type -> hookwatch.webhook.v1.CreateEventRequest
	2, // 5: hookwatch.webhook.v1.WebhookService.GetEndpointBySlug:output_type -> hookwatch.webhook.v1.GetEndpointBySlugResponse
	4, // 6: hookwatch.webhook.v1.WebhookService.CreateEvent:output_type -> hookwatch.webhook.v1.CreateEventResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_webhook_v1_webhook_proto_init() }
func file_webhook_v1_webhook_proto_init() {
	if File_webhook_v1_webhook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webhook_v1_webhook_proto_rawDesc), len(file_webhook_v1_webhook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webhook_v1_webhook_proto_goTypes,
		DependencyIndexes: file_webhook_v1_webhook_proto_depIdxs,
		MessageInfos:      file_webhook_v1_webhook_proto_msgTypes,
	}.Build()
	File_webhook_v1_webhook_proto = out.File
	file_webhook_v1_webhook_proto_goTypes = nil
	file_webhook_v1_webhook_proto_depIdxs = nil
}
