// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: alert.proto

package cliv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Alert represents an alert configuration.
type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EndpointId    string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{0}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *Alert) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Alert) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Alert) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Alert) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Alert) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsRequest) Reset() {
	*x = ListAlertsRequest{}
	mi := &file_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsRequest) ProtoMessage() {}

func (x *ListAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsRequest.ProtoReflect.Descriptor instead.
func (*ListAlertsRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{1}
}

func (x *ListAlertsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ListAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlertsResponse) Reset() {
	*x = ListAlertsResponse{}
	mi := &file_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlertsResponse) ProtoMessage() {}

func (x *ListAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlertsResponse.ProtoReflect.Descriptor instead.
func (*ListAlertsResponse) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{2}
}

func (x *ListAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

type GetAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRequest) Reset() {
	*x = GetAlertRequest{}
	mi := &file_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRequest) ProtoMessage() {}

func (x *GetAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{3}
}

func (x *GetAlertRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertResponse) Reset() {
	*x = GetAlertResponse{}
	mi := &file_alert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertResponse) ProtoMessage() {}

func (x *GetAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertResponse.ProtoReflect.Descriptor instead.
func (*GetAlertResponse) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{4}
}

func (x *GetAlertResponse) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

type CreateAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	EndpointId    string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Target        string                 `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRequest) Reset() {
	*x = CreateAlertRequest{}
	mi := &file_alert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRequest) ProtoMessage() {}

func (x *CreateAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAlertRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateAlertRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *CreateAlertRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateAlertRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type CreateAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertResponse) Reset() {
	*x = CreateAlertResponse{}
	mi := &file_alert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertResponse) ProtoMessage() {}

func (x *CreateAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertResponse) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAlertResponse) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

type UpdateAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	EndpointId    string                 `protobuf:"bytes,3,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Target        string                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertRequest) Reset() {
	*x = UpdateAlertRequest{}
	mi := &file_alert_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertRequest) ProtoMessage() {}

func (x *UpdateAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlertRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAlertRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *UpdateAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAlertRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *UpdateAlertRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateAlertRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UpdateAlertRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlertResponse) Reset() {
	*x = UpdateAlertResponse{}
	mi := &file_alert_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlertResponse) ProtoMessage() {}

func (x *UpdateAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlertResponse.ProtoReflect.Descriptor instead.
func (*UpdateAlertResponse) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAlertResponse) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

type DeleteAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertRequest) Reset() {
	*x = DeleteAlertRequest{}
	mi := &file_alert_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertRequest) ProtoMessage() {}

func (x *DeleteAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertRequest.ProtoReflect.Descriptor instead.
func (*DeleteAlertRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAlertRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DeleteAlertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAlertResponse) Reset() {
	*x = DeleteAlertResponse{}
	mi := &file_alert_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAlertResponse) ProtoMessage() {}

func (x *DeleteAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAlertResponse.ProtoReflect.Descriptor instead.
func (*DeleteAlertResponse) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{10}
}

type GetAlertsByEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	EndpointId    string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsByEndpointRequest) Reset() {
	*x = GetAlertsByEndpointRequest{}
	mi := &file_alert_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsByEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsByEndpointRequest) ProtoMessage() {}

func (x *GetAlertsByEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsByEndpointRequest.ProtoReflect.Descriptor instead.
func (*GetAlertsByEndpointRequest) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{11}
}

func (x *GetAlertsByEndpointRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetAlertsByEndpointRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type GetAlertsByEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertsByEndpointResponse) Reset() {
	*x = GetAlertsByEndpointResponse{}
	mi := &file_alert_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertsByEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertsByEndpointResponse) ProtoMessage() {}

func (x *GetAlertsByEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertsByEndpointResponse.ProtoReflect.Descriptor instead.
func (*GetAlertsByEndpointResponse) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{12}
}

func (x *GetAlertsByEndpointResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

var File_alert_proto protoreflect.FileDescriptor

const file_alert_proto_rawDesc = "" +
	"\n" +
	"\valert.proto\x12\x10hookwatch.cli.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x01\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\",\n" +
	"\x11ListAlertsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"E\n" +
	"\x12ListAlertsResponse\x12/\n" +
	"\x06alerts\x18\x01 \x03(\v2\x17.hookwatch.cli.v1.AlertR\x06alerts\":\n" +
	"\x0fGetAlertRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"A\n" +
	"\x10GetAlertResponse\x12-\n" +
	"\x05alert\x18\x01 \x01(\v2\x17.hookwatch.cli.v1.AlertR\x05alert\"z\n" +
	"\x12CreateAlertRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\"D\n" +
	"\x13CreateAlertResponse\x12-\n" +
	"\x05alert\x18\x01 \x01(\v2\x17.hookwatch.cli.v1.AlertR\x05alert\"\xa7\x01\n" +
	"\x12UpdateAlertRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1f\n" +
	"\vendpoint_id\x18\x03 \x01(\tR\n" +
	"endpointId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"D\n" +
	"\x13UpdateAlertResponse\x12-\n" +
	"\x05alert\x18\x01 \x01(\v2\x17.hookwatch.cli.v1.AlertR\x05alert\"=\n" +
	"\x12DeleteAlertRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteAlertResponse\"V\n" +
	"\x1aGetAlertsByEndpointRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\"N\n" +
	"\x1bGetAlertsByEndpointResponse\x12/\n" +
	"\x06alerts\x18\x01 \x03(\v2\x17.hookwatch.cli.v1.AlertR\x06alerts2\xc2\x04\n" +
	"\fAlertService\x12W\n" +
	"\n" +
	"ListAlerts\x12#.hookwatch.cli.v1.ListAlertsRequest\x1a$.hookwatch.cli.v1.ListAlertsResponse\x12Q\n" +
	"\bGetAlert\x12!.hookwatch.cli.v1.GetAlertRequest\x1a\".hookwatch.cli.v1.GetAlertResponse\x12Z\n" +
	"\vCreateAlert\x12$.hookwatch.cli.v1.CreateAlertRequest\x1a%.hookwatch.cli.v1.CreateAlertResponse\x12Z\n" +
	"\vUpdateAlert\x12$.hookwatch.cli.v1.UpdateAlertRequest\x1a%.hookwatch.cli.v1.UpdateAlertResponse\x12Z\n" +
	"\vDeleteAlert\x12$.hookwatch.cli.v1.DeleteAlertRequest\x1a%.hookwatch.cli.v1.DeleteAlertResponse\x12r\n" +
	"\x13GetAlertsByEndpoint\x12,.hookwatch.cli.v1.GetAlertsByEndpointRequest\x1a-.hookwatch.cli.v1.GetAlertsByEndpointResponseB-Z+github.com/hookwatch-dev/proto/cli/v1;cliv1b\x06proto3"

var (
	file_alert_proto_rawDescOnce sync.Once
	file_alert_proto_rawDescData []byte
)

func file_alert_proto_rawDescGZIP() []byte {
	file_alert_proto_rawDescOnce.Do(func() {
		file_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alert_proto_rawDesc), len(file_alert_proto_rawDesc)))
	})
	return file_alert_proto_rawDescData
}

var file_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_alert_proto_goTypes = []any{
	(*Alert)(nil),                       // 0: hookwatch.cli.v1.Alert
	(*ListAlertsRequest)(nil),           // 1: hookwatch.cli.v1.ListAlertsRequest
	(*ListAlertsResponse)(nil),          // 2: hookwatch.cli.v1.ListAlertsResponse
	(*GetAlertRequest)(nil),             // 3: hookwatch.cli.v1.GetAlertRequest
	(*GetAlertResponse)(nil),            // 4: hookwatch.cli.v1.GetAlertResponse
	(*CreateAlertRequest)(nil),          // 5: hookwatch.cli.v1.CreateAlertRequest
	(*CreateAlertResponse)(nil),         // 6: hookwatch.cli.v1.CreateAlertResponse
	(*UpdateAlertRequest)(nil),          // 7: hookwatch.cli.v1.UpdateAlertRequest
	(*UpdateAlertResponse)(nil),         // 8: hookwatch.cli.v1.UpdateAlertResponse
	(*DeleteAlertRequest)(nil),          // 9: hookwatch.cli.v1.DeleteAlertRequest
	(*DeleteAlertResponse)(nil),         // 10: hookwatch.cli.v1.DeleteAlertResponse
	(*GetAlertsByEndpointRequest)(nil),  // 11: hookwatch.cli.v1.GetAlertsByEndpointRequest
	(*GetAlertsByEndpointResponse)(nil), // 12: hookwatch.cli.v1.GetAlertsByEndpointResponse
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
}
var file_alert_proto_depIdxs = []int32{
	13, // 0: hookwatch.cli.v1.Alert.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: hookwatch.cli.v1.Alert.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: hookwatch.cli.v1.ListAlertsResponse.alerts:type_name -> hookwatch.cli.v1.Alert
	0,  // 3: hookwatch.cli.v1.GetAlertResponse.alert:type_name -> hookwatch.cli.v1.Alert
	0,  // 4: hookwatch.cli.v1.CreateAlertResponse.alert:type_name -> hookwatch.cli.v1.Alert
	0,  // 5: hookwatch.cli.v1.UpdateAlertResponse.alert:type_name -> hookwatch.cli.v1.Alert
	0,  // 6: hookwatch.cli.v1.GetAlertsByEndpointResponse.alerts:type_name -> hookwatch.cli.v1.Alert
	1,  // 7: hookwatch.cli.v1.AlertService.ListAlerts:input_type -> hookwatch.cli.v1.ListAlertsRequest
	3,  // 8: hookwatch.cli.v1.AlertService.GetAlert:input_type -> hookwatch.cli.v1.GetAlertRequest
	5,  // 9: hookwatch.cli.v1.AlertService.CreateAlert:input_type -> hookwatch.cli.v1.CreateAlertRequest
	7,  // 10: hookwatch.cli.v1.AlertService.UpdateAlert:input_type -> hookwatch.cli.v1.UpdateAlertRequest
	9,  // 11: hookwatch.cli.v1.AlertService.DeleteAlert:input_type -> hookwatch.cli.v1.DeleteAlertRequest
	11, // 12: hookwatch.cli.v1.AlertService.GetAlertsByEndpoint:input_type -> hookwatch.cli.v1.GetAlertsByEndpointRequest
	2,  // 13: hookwatch.cli.v1.AlertService.ListAlerts:output_type -> hookwatch.cli.v1.ListAlertsResponse
	4,  // 14: hookwatch.cli.v1.AlertService.GetAlert:output_type -> hookwatch.cli.v1.GetAlertResponse
	6,  // 15: hookwatch.cli.v1.AlertService.CreateAlert:output_type -> hookwatch.cli.v1.CreateAlertResponse
	8,  // 16: hookwatch.cli.v1.AlertService.UpdateAlert:output_type -> hookwatch.cli.v1.UpdateAlertResponse
	10, // 17: hookwatch.cli.v1.AlertService.DeleteAlert:output_type -> hookwatch.cli.v1.DeleteAlertResponse
	12, // 18: hookwatch.cli.v1.AlertService.GetAlertsByEndpoint:output_type -> hookwatch.cli.v1.GetAlertsByEndpointResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_alert_proto_init() }
func file_alert_proto_init() {
	if File_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alert_proto_rawDesc), len(file_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alert_proto_goTypes,
		DependencyIndexes: file_alert_proto_depIdxs,
		MessageInfos:      file_alert_proto_msgTypes,
	}.Build()
	File_alert_proto = out.File
	file_alert_proto_goTypes = nil
	file_alert_proto_depIdxs = nil
}
