// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: apikey.proto

package cliv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// APIKey represents an API key.
type APIKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	LastUsedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKey) Reset() {
	*x = APIKey{}
	mi := &file_apikey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKey) ProtoMessage() {}

func (x *APIKey) ProtoReflect() protoreflect.Message {
	mi := &file_apikey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKey.ProtoReflect.Descriptor instead.
func (*APIKey) Descriptor() ([]byte, []int) {
	return file_apikey_proto_rawDescGZIP(), []int{0}
}

func (x *APIKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *APIKey) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *APIKey) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *APIKey) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *APIKey) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *APIKey) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *APIKey) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *APIKey) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListAPIKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysRequest) Reset() {
	*x = ListAPIKeysRequest{}
	mi := &file_apikey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysRequest) ProtoMessage() {}

func (x *ListAPIKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apikey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysRequest.ProtoReflect.Descriptor instead.
func (*ListAPIKeysRequest) Descriptor() ([]byte, []int) {
	return file_apikey_proto_rawDescGZIP(), []int{1}
}

func (x *ListAPIKeysRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ListAPIKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*APIKey              `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAPIKeysResponse) Reset() {
	*x = ListAPIKeysResponse{}
	mi := &file_apikey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAPIKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAPIKeysResponse) ProtoMessage() {}

func (x *ListAPIKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apikey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAPIKeysResponse.ProtoReflect.Descriptor instead.
func (*ListAPIKeysResponse) Descriptor() ([]byte, []int) {
	return file_apikey_proto_rawDescGZIP(), []int{2}
}

func (x *ListAPIKeysResponse) GetKeys() []*APIKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type GetAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIKeyRequest) Reset() {
	*x = GetAPIKeyRequest{}
	mi := &file_apikey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIKeyRequest) ProtoMessage() {}

func (x *GetAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apikey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*GetAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_apikey_proto_rawDescGZIP(), []int{3}
}

func (x *GetAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *APIKey                `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIKeyResponse) Reset() {
	*x = GetAPIKeyResponse{}
	mi := &file_apikey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIKeyResponse) ProtoMessage() {}

func (x *GetAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apikey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*GetAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_apikey_proto_rawDescGZIP(), []int{4}
}

func (x *GetAPIKeyResponse) GetKey() *APIKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type CreateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_apikey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apikey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_apikey_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *APIKey                `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyResponse) Reset() {
	*x = CreateAPIKeyResponse{}
	mi := &file_apikey_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyResponse) ProtoMessage() {}

func (x *CreateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apikey_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_apikey_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAPIKeyResponse) GetKey() *APIKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyRequest) Reset() {
	*x = DeleteAPIKeyRequest{}
	mi := &file_apikey_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyRequest) ProtoMessage() {}

func (x *DeleteAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apikey_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_apikey_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DeleteAPIKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAPIKeyResponse) Reset() {
	*x = DeleteAPIKeyResponse{}
	mi := &file_apikey_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAPIKeyResponse) ProtoMessage() {}

func (x *DeleteAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apikey_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_apikey_proto_rawDescGZIP(), []int{8}
}

var File_apikey_proto protoreflect.FileDescriptor

const file_apikey_proto_rawDesc = "" +
	"\n" +
	"\fapikey.proto\x12\x10hookwatch.cli.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x02\n" +
	"\x06APIKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12<\n" +
	"\flast_used_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"-\n" +
	"\x12ListAPIKeysRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"C\n" +
	"\x13ListAPIKeysResponse\x12,\n" +
	"\x04keys\x18\x01 \x03(\v2\x18.hookwatch.cli.v1.APIKeyR\x04keys\";\n" +
	"\x10GetAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"?\n" +
	"\x11GetAPIKeyResponse\x12*\n" +
	"\x03key\x18\x01 \x01(\v2\x18.hookwatch.cli.v1.APIKeyR\x03key\"}\n" +
	"\x13CreateAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"B\n" +
	"\x14CreateAPIKeyResponse\x12*\n" +
	"\x03key\x18\x01 \x01(\v2\x18.hookwatch.cli.v1.APIKeyR\x03key\">\n" +
	"\x13DeleteAPIKeyRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteAPIKeyResponse2\xff\x02\n" +
	"\rAPIKeyService\x12Z\n" +
	"\vListAPIKeys\x12$.hookwatch.cli.v1.ListAPIKeysRequest\x1a%.hookwatch.cli.v1.ListAPIKeysResponse\x12T\n" +
	"\tGetAPIKey\x12\".hookwatch.cli.v1.GetAPIKeyRequest\x1a#.hookwatch.cli.v1.GetAPIKeyResponse\x12]\n" +
	"\fCreateAPIKey\x12%.hookwatch.cli.v1.CreateAPIKeyRequest\x1a&.hookwatch.cli.v1.CreateAPIKeyResponse\x12]\n" +
	"\fDeleteAPIKey\x12%.hookwatch.cli.v1.DeleteAPIKeyRequest\x1a&.hookwatch.cli.v1.DeleteAPIKeyResponseB-Z+github.com/hookwatch-dev/proto/cli/v1;cliv1b\x06proto3"

var (
	file_apikey_proto_rawDescOnce sync.Once
	file_apikey_proto_rawDescData []byte
)

func file_apikey_proto_rawDescGZIP() []byte {
	file_apikey_proto_rawDescOnce.Do(func() {
		file_apikey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apikey_proto_rawDesc), len(file_apikey_proto_rawDesc)))
	})
	return file_apikey_proto_rawDescData
}

var file_apikey_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_apikey_proto_goTypes = []any{
	(*APIKey)(nil),                // 0: hookwatch.cli.v1.APIKey
	(*ListAPIKeysRequest)(nil),    // 1: hookwatch.cli.v1.ListAPIKeysRequest
	(*ListAPIKeysResponse)(nil),   // 2: hookwatch.cli.v1.ListAPIKeysResponse
	(*GetAPIKeyRequest)(nil),      // 3: hookwatch.cli.v1.GetAPIKeyRequest
	(*GetAPIKeyResponse)(nil),     // 4: hookwatch.cli.v1.GetAPIKeyResponse
	(*CreateAPIKeyRequest)(nil),   // 5: hookwatch.cli.v1.CreateAPIKeyRequest
	(*CreateAPIKeyResponse)(nil),  // 6: hookwatch.cli.v1.CreateAPIKeyResponse
	(*DeleteAPIKeyRequest)(nil),   // 7: hookwatch.cli.v1.DeleteAPIKeyRequest
	(*DeleteAPIKeyResponse)(nil),  // 8: hookwatch.cli.v1.DeleteAPIKeyResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_apikey_proto_depIdxs = []int32{
	9,  // 0: hookwatch.cli.v1.APIKey.last_used_at:type_name -> google.protobuf.Timestamp
	9,  // 1: hookwatch.cli.v1.APIKey.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 2: hookwatch.cli.v1.APIKey.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: hookwatch.cli.v1.APIKey.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: hookwatch.cli.v1.ListAPIKeysResponse.keys:type_name -> hookwatch.cli.v1.APIKey
	0,  // 5: hookwatch.cli.v1.GetAPIKeyResponse.key:type_name -> hookwatch.cli.v1.APIKey
	9,  // 6: hookwatch.cli.v1.CreateAPIKeyRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 7: hookwatch.cli.v1.CreateAPIKeyResponse.key:type_name -> hookwatch.cli.v1.APIKey
	1,  // 8: hookwatch.cli.v1.APIKeyService.ListAPIKeys:input_type -> hookwatch.cli.v1.ListAPIKeysRequest
	3,  // 9: hookwatch.cli.v1.APIKeyService.GetAPIKey:input_type -> hookwatch.cli.v1.GetAPIKeyRequest
	5,  // 10: hookwatch.cli.v1.APIKeyService.CreateAPIKey:input_type -> hookwatch.cli.v1.CreateAPIKeyRequest
	7,  // 11: hookwatch.cli.v1.APIKeyService.DeleteAPIKey:input_type -> hookwatch.cli.v1.DeleteAPIKeyRequest
	2,  // 12: hookwatch.cli.v1.APIKeyService.ListAPIKeys:output_type -> hookwatch.cli.v1.ListAPIKeysResponse
	4,  // 13: hookwatch.cli.v1.APIKeyService.GetAPIKey:output_type -> hookwatch.cli.v1.GetAPIKeyResponse
	6,  // 14: hookwatch.cli.v1.APIKeyService.CreateAPIKey:output_type -> hookwatch.cli.v1.CreateAPIKeyResponse
	8,  // 15: hookwatch.cli.v1.APIKeyService.DeleteAPIKey:output_type -> hookwatch.cli.v1.DeleteAPIKeyResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_apikey_proto_init() }
func file_apikey_proto_init() {
	if File_apikey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apikey_proto_rawDesc), len(file_apikey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apikey_proto_goTypes,
		DependencyIndexes: file_apikey_proto_depIdxs,
		MessageInfos:      file_apikey_proto_msgTypes,
	}.Build()
	File_apikey_proto = out.File
	file_apikey_proto_goTypes = nil
	file_apikey_proto_depIdxs = nil
}
