// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: cli/v1/cli.proto

package cliv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CLIRequest represents messages from CLI client to server
type CLIRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*CLIRequest_Authenticate
	//	*CLIRequest_Subscribe
	//	*CLIRequest_Unsubscribe
	//	*CLIRequest_Ack
	//	*CLIRequest_Ping
	Request       isCLIRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLIRequest) Reset() {
	*x = CLIRequest{}
	mi := &file_cli_v1_cli_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLIRequest) ProtoMessage() {}

func (x *CLIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLIRequest.ProtoReflect.Descriptor instead.
func (*CLIRequest) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{0}
}

func (x *CLIRequest) GetRequest() isCLIRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CLIRequest) GetAuthenticate() *AuthenticateRequest {
	if x != nil {
		if x, ok := x.Request.(*CLIRequest_Authenticate); ok {
			return x.Authenticate
		}
	}
	return nil
}

func (x *CLIRequest) GetSubscribe() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Request.(*CLIRequest_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *CLIRequest) GetUnsubscribe() *UnsubscribeRequest {
	if x != nil {
		if x, ok := x.Request.(*CLIRequest_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *CLIRequest) GetAck() *AckRequest {
	if x != nil {
		if x, ok := x.Request.(*CLIRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *CLIRequest) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Request.(*CLIRequest_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isCLIRequest_Request interface {
	isCLIRequest_Request()
}

type CLIRequest_Authenticate struct {
	Authenticate *AuthenticateRequest `protobuf:"bytes,1,opt,name=authenticate,proto3,oneof"`
}

type CLIRequest_Subscribe struct {
	Subscribe *SubscribeRequest `protobuf:"bytes,2,opt,name=subscribe,proto3,oneof"`
}

type CLIRequest_Unsubscribe struct {
	Unsubscribe *UnsubscribeRequest `protobuf:"bytes,3,opt,name=unsubscribe,proto3,oneof"`
}

type CLIRequest_Ack struct {
	Ack *AckRequest `protobuf:"bytes,4,opt,name=ack,proto3,oneof"`
}

type CLIRequest_Ping struct {
	Ping *PingRequest `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

func (*CLIRequest_Authenticate) isCLIRequest_Request() {}

func (*CLIRequest_Subscribe) isCLIRequest_Request() {}

func (*CLIRequest_Unsubscribe) isCLIRequest_Request() {}

func (*CLIRequest_Ack) isCLIRequest_Request() {}

func (*CLIRequest_Ping) isCLIRequest_Request() {}

// AuthenticateRequest authenticates the CLI session using an API key
type AuthenticateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API key in format hk_xxxxx
	ApiKey        string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_cli_v1_cli_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{1}
}

func (x *AuthenticateRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// SubscribeRequest subscribes to events for an endpoint
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*SubscribeRequest_EndpointId
	//	*SubscribeRequest_Slug
	Identifier    isSubscribeRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_cli_v1_cli_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetIdentifier() isSubscribeRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *SubscribeRequest) GetEndpointId() string {
	if x != nil {
		if x, ok := x.Identifier.(*SubscribeRequest_EndpointId); ok {
			return x.EndpointId
		}
	}
	return ""
}

func (x *SubscribeRequest) GetSlug() string {
	if x != nil {
		if x, ok := x.Identifier.(*SubscribeRequest_Slug); ok {
			return x.Slug
		}
	}
	return ""
}

type isSubscribeRequest_Identifier interface {
	isSubscribeRequest_Identifier()
}

type SubscribeRequest_EndpointId struct {
	EndpointId string `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3,oneof"` // Subscribe by endpoint UUID
}

type SubscribeRequest_Slug struct {
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3,oneof"` // Subscribe by endpoint slug
}

func (*SubscribeRequest_EndpointId) isSubscribeRequest_Identifier() {}

func (*SubscribeRequest_Slug) isSubscribeRequest_Identifier() {}

// UnsubscribeRequest unsubscribes from an endpoint
type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_cli_v1_cli_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{3}
}

func (x *UnsubscribeRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

// AckRequest acknowledges successful receipt and forwarding of an event
type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                              // Whether forward to localhost succeeded
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`      // HTTP status from localhost
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_cli_v1_cli_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{4}
}

func (x *AckRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AckRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AckRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AckRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// PingRequest keeps the connection alive
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_cli_v1_cli_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{5}
}

// CLIResponse represents messages from server to CLI client
type CLIResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*CLIResponse_Authenticate
	//	*CLIResponse_Subscribe
	//	*CLIResponse_Unsubscribe
	//	*CLIResponse_Event
	//	*CLIResponse_Pong
	//	*CLIResponse_Error
	Response      isCLIResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLIResponse) Reset() {
	*x = CLIResponse{}
	mi := &file_cli_v1_cli_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLIResponse) ProtoMessage() {}

func (x *CLIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLIResponse.ProtoReflect.Descriptor instead.
func (*CLIResponse) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{6}
}

func (x *CLIResponse) GetResponse() isCLIResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CLIResponse) GetAuthenticate() *AuthenticateResponse {
	if x != nil {
		if x, ok := x.Response.(*CLIResponse_Authenticate); ok {
			return x.Authenticate
		}
	}
	return nil
}

func (x *CLIResponse) GetSubscribe() *SubscribeResponse {
	if x != nil {
		if x, ok := x.Response.(*CLIResponse_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *CLIResponse) GetUnsubscribe() *UnsubscribeResponse {
	if x != nil {
		if x, ok := x.Response.(*CLIResponse_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *CLIResponse) GetEvent() *WebhookEvent {
	if x != nil {
		if x, ok := x.Response.(*CLIResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *CLIResponse) GetPong() *PongResponse {
	if x != nil {
		if x, ok := x.Response.(*CLIResponse_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *CLIResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Response.(*CLIResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCLIResponse_Response interface {
	isCLIResponse_Response()
}

type CLIResponse_Authenticate struct {
	Authenticate *AuthenticateResponse `protobuf:"bytes,1,opt,name=authenticate,proto3,oneof"`
}

type CLIResponse_Subscribe struct {
	Subscribe *SubscribeResponse `protobuf:"bytes,2,opt,name=subscribe,proto3,oneof"`
}

type CLIResponse_Unsubscribe struct {
	Unsubscribe *UnsubscribeResponse `protobuf:"bytes,3,opt,name=unsubscribe,proto3,oneof"`
}

type CLIResponse_Event struct {
	Event *WebhookEvent `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

type CLIResponse_Pong struct {
	Pong *PongResponse `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

type CLIResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*CLIResponse_Authenticate) isCLIResponse_Response() {}

func (*CLIResponse_Subscribe) isCLIResponse_Response() {}

func (*CLIResponse_Unsubscribe) isCLIResponse_Response() {}

func (*CLIResponse_Event) isCLIResponse_Response() {}

func (*CLIResponse_Pong) isCLIResponse_Response() {}

func (*CLIResponse_Error) isCLIResponse_Response() {}

// AuthenticateResponse confirms authentication
type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_cli_v1_cli_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{7}
}

func (x *AuthenticateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthenticateResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthenticateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SubscribeResponse confirms subscription to an endpoint
type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EndpointId    string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	EndpointName  string                 `protobuf:"bytes,3,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_cli_v1_cli_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubscribeResponse) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *SubscribeResponse) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

func (x *SubscribeResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *SubscribeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UnsubscribeResponse confirms unsubscription
type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EndpointId    string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_cli_v1_cli_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{9}
}

func (x *UnsubscribeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnsubscribeResponse) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

// WebhookEvent represents an incoming webhook to forward to localhost
type WebhookEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EndpointId    string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	EndpointName  string                 `protobuf:"bytes,3,opt,name=endpoint_name,json=endpointName,proto3" json:"endpoint_name,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	SourceIp      string                 `protobuf:"bytes,8,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookEvent) Reset() {
	*x = WebhookEvent{}
	mi := &file_cli_v1_cli_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEvent) ProtoMessage() {}

func (x *WebhookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEvent.ProtoReflect.Descriptor instead.
func (*WebhookEvent) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{10}
}

func (x *WebhookEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *WebhookEvent) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *WebhookEvent) GetEndpointName() string {
	if x != nil {
		return x.EndpointName
	}
	return ""
}

func (x *WebhookEvent) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *WebhookEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *WebhookEvent) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *WebhookEvent) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WebhookEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *WebhookEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// PongResponse responds to ping
type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_cli_v1_cli_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{11}
}

// ErrorResponse contains error details
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_cli_v1_cli_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cli_v1_cli_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_cli_v1_cli_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cli_v1_cli_proto protoreflect.FileDescriptor

const file_cli_v1_cli_proto_rawDesc = "" +
	"\n" +
	"\x10cli/v1/cli.proto\x12\x10hookwatch.cli.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x02\n" +
	"\n" +
	"CLIRequest\x12K\n" +
	"\fauthenticate\x18\x01 \x01(\v2%.hookwatch.cli.v1.AuthenticateRequestH\x00R\fauthenticate\x12B\n" +
	"\tsubscribe\x18\x02 \x01(\v2\".hookwatch.cli.v1.SubscribeRequestH\x00R\tsubscribe\x12H\n" +
	"\vunsubscribe\x18\x03 \x01(\v2$.hookwatch.cli.v1.UnsubscribeRequestH\x00R\vunsubscribe\x120\n" +
	"\x03ack\x18\x04 \x01(\v2\x1c.hookwatch.cli.v1.AckRequestH\x00R\x03ack\x123\n" +
	"\x04ping\x18\x05 \x01(\v2\x1d.hookwatch.cli.v1.PingRequestH\x00R\x04pingB\t\n" +
	"\arequest\".\n" +
	"\x13AuthenticateRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"Y\n" +
	"\x10SubscribeRequest\x12!\n" +
	"\vendpoint_id\x18\x01 \x01(\tH\x00R\n" +
	"endpointId\x12\x14\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slugB\f\n" +
	"\n" +
	"identifier\"5\n" +
	"\x12UnsubscribeRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\"\x87\x01\n" +
	"\n" +
	"AckRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\r\n" +
	"\vPingRequest\"\x9e\x03\n" +
	"\vCLIResponse\x12L\n" +
	"\fauthenticate\x18\x01 \x01(\v2&.hookwatch.cli.v1.AuthenticateResponseH\x00R\fauthenticate\x12C\n" +
	"\tsubscribe\x18\x02 \x01(\v2#.hookwatch.cli.v1.SubscribeResponseH\x00R\tsubscribe\x12I\n" +
	"\vunsubscribe\x18\x03 \x01(\v2%.hookwatch.cli.v1.UnsubscribeResponseH\x00R\vunsubscribe\x126\n" +
	"\x05event\x18\x04 \x01(\v2\x1e.hookwatch.cli.v1.WebhookEventH\x00R\x05event\x124\n" +
	"\x04pong\x18\x05 \x01(\v2\x1e.hookwatch.cli.v1.PongResponseH\x00R\x04pong\x127\n" +
	"\x05error\x18\x06 \x01(\v2\x1f.hookwatch.cli.v1.ErrorResponseH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"_\n" +
	"\x14AuthenticateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x9d\x01\n" +
	"\x11SubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12#\n" +
	"\rendpoint_name\x18\x03 \x01(\tR\fendpointName\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"P\n" +
	"\x13UnsubscribeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\"\x8a\x03\n" +
	"\fWebhookEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12#\n" +
	"\rendpoint_name\x18\x03 \x01(\tR\fendpointName\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12E\n" +
	"\aheaders\x18\x06 \x03(\v2+.hookwatch.cli.v1.WebhookEvent.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x12\x1b\n" +
	"\tsource_ip\x18\b \x01(\tR\bsourceIp\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fPongResponse\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\\\n" +
	"\n" +
	"CLIService\x12N\n" +
	"\vEventStream\x12\x1c.hookwatch.cli.v1.CLIRequest\x1a\x1d.hookwatch.cli.v1.CLIResponse(\x010\x01B-Z+github.com/hookwatch-dev/proto/cli/v1;cliv1b\x06proto3"

var (
	file_cli_v1_cli_proto_rawDescOnce sync.Once
	file_cli_v1_cli_proto_rawDescData []byte
)

func file_cli_v1_cli_proto_rawDescGZIP() []byte {
	file_cli_v1_cli_proto_rawDescOnce.Do(func() {
		file_cli_v1_cli_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cli_v1_cli_proto_rawDesc), len(file_cli_v1_cli_proto_rawDesc)))
	})
	return file_cli_v1_cli_proto_rawDescData
}

var file_cli_v1_cli_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_cli_v1_cli_proto_goTypes = []any{
	(*CLIRequest)(nil),            // 0: hookwatch.cli.v1.CLIRequest
	(*AuthenticateRequest)(nil),   // 1: hookwatch.cli.v1.AuthenticateRequest
	(*SubscribeRequest)(nil),      // 2: hookwatch.cli.v1.SubscribeRequest
	(*UnsubscribeRequest)(nil),    // 3: hookwatch.cli.v1.UnsubscribeRequest
	(*AckRequest)(nil),            // 4: hookwatch.cli.v1.AckRequest
	(*PingRequest)(nil),           // 5: hookwatch.cli.v1.PingRequest
	(*CLIResponse)(nil),           // 6: hookwatch.cli.v1.CLIResponse
	(*AuthenticateResponse)(nil),  // 7: hookwatch.cli.v1.AuthenticateResponse
	(*SubscribeResponse)(nil),     // 8: hookwatch.cli.v1.SubscribeResponse
	(*UnsubscribeResponse)(nil),   // 9: hookwatch.cli.v1.UnsubscribeResponse
	(*WebhookEvent)(nil),          // 10: hookwatch.cli.v1.WebhookEvent
	(*PongResponse)(nil),          // 11: hookwatch.cli.v1.PongResponse
	(*ErrorResponse)(nil),         // 12: hookwatch.cli.v1.ErrorResponse
	nil,                           // 13: hookwatch.cli.v1.WebhookEvent.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_cli_v1_cli_proto_depIdxs = []int32{
	1,  // 0: hookwatch.cli.v1.CLIRequest.authenticate:type_name -> hookwatch.cli.v1.AuthenticateRequest
	2,  // 1: hookwatch.cli.v1.CLIRequest.subscribe:type_name -> hookwatch.cli.v1.SubscribeRequest
	3,  // 2: hookwatch.cli.v1.CLIRequest.unsubscribe:type_name -> hookwatch.cli.v1.UnsubscribeRequest
	4,  // 3: hookwatch.cli.v1.CLIRequest.ack:type_name -> hookwatch.cli.v1.AckRequest
	5,  // 4: hookwatch.cli.v1.CLIRequest.ping:type_name -> hookwatch.cli.v1.PingRequest
	7,  // 5: hookwatch.cli.v1.CLIResponse.authenticate:type_name -> hookwatch.cli.v1.AuthenticateResponse
	8,  // 6: hookwatch.cli.v1.CLIResponse.subscribe:type_name -> hookwatch.cli.v1.SubscribeResponse
	9,  // 7: hookwatch.cli.v1.CLIResponse.unsubscribe:type_name -> hookwatch.cli.v1.UnsubscribeResponse
	10, // 8: hookwatch.cli.v1.CLIResponse.event:type_name -> hookwatch.cli.v1.WebhookEvent
	11, // 9: hookwatch.cli.v1.CLIResponse.pong:type_name -> hookwatch.cli.v1.PongResponse
	12, // 10: hookwatch.cli.v1.CLIResponse.error:type_name -> hookwatch.cli.v1.ErrorResponse
	13, // 11: hookwatch.cli.v1.WebhookEvent.headers:type_name -> hookwatch.cli.v1.WebhookEvent.HeadersEntry
	14, // 12: hookwatch.cli.v1.WebhookEvent.created_at:type_name -> google.protobuf.Timestamp
	0,  // 13: hookwatch.cli.v1.CLIService.EventStream:input_type -> hookwatch.cli.v1.CLIRequest
	6,  // 14: hookwatch.cli.v1.CLIService.EventStream:output_type -> hookwatch.cli.v1.CLIResponse
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cli_v1_cli_proto_init() }
func file_cli_v1_cli_proto_init() {
	if File_cli_v1_cli_proto != nil {
		return
	}
	file_cli_v1_cli_proto_msgTypes[0].OneofWrappers = []any{
		(*CLIRequest_Authenticate)(nil),
		(*CLIRequest_Subscribe)(nil),
		(*CLIRequest_Unsubscribe)(nil),
		(*CLIRequest_Ack)(nil),
		(*CLIRequest_Ping)(nil),
	}
	file_cli_v1_cli_proto_msgTypes[2].OneofWrappers = []any{
		(*SubscribeRequest_EndpointId)(nil),
		(*SubscribeRequest_Slug)(nil),
	}
	file_cli_v1_cli_proto_msgTypes[6].OneofWrappers = []any{
		(*CLIResponse_Authenticate)(nil),
		(*CLIResponse_Subscribe)(nil),
		(*CLIResponse_Unsubscribe)(nil),
		(*CLIResponse_Event)(nil),
		(*CLIResponse_Pong)(nil),
		(*CLIResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cli_v1_cli_proto_rawDesc), len(file_cli_v1_cli_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cli_v1_cli_proto_goTypes,
		DependencyIndexes: file_cli_v1_cli_proto_depIdxs,
		MessageInfos:      file_cli_v1_cli_proto_msgTypes,
	}.Build()
	File_cli_v1_cli_proto = out.File
	file_cli_v1_cli_proto_goTypes = nil
	file_cli_v1_cli_proto_depIdxs = nil
}
