// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: cli/v1/cli.proto

package cliv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CLIService_EventStream_FullMethodName = "/hookwatch.cli.v1.CLIService/EventStream"
)

// CLIServiceClient is the client API for CLIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CLIService handles bidirectional streaming for CLI clients
type CLIServiceClient interface {
	// EventStream establishes a bidirectional stream for receiving webhook events
	EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CLIRequest, CLIResponse], error)
}

type cLIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCLIServiceClient(cc grpc.ClientConnInterface) CLIServiceClient {
	return &cLIServiceClient{cc}
}

func (c *cLIServiceClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CLIRequest, CLIResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CLIService_ServiceDesc.Streams[0], CLIService_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CLIRequest, CLIResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CLIService_EventStreamClient = grpc.BidiStreamingClient[CLIRequest, CLIResponse]

// CLIServiceServer is the server API for CLIService service.
// All implementations must embed UnimplementedCLIServiceServer
// for forward compatibility.
//
// CLIService handles bidirectional streaming for CLI clients
type CLIServiceServer interface {
	// EventStream establishes a bidirectional stream for receiving webhook events
	EventStream(grpc.BidiStreamingServer[CLIRequest, CLIResponse]) error
	mustEmbedUnimplementedCLIServiceServer()
}

// UnimplementedCLIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCLIServiceServer struct{}

func (UnimplementedCLIServiceServer) EventStream(grpc.BidiStreamingServer[CLIRequest, CLIResponse]) error {
	return status.Error(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedCLIServiceServer) mustEmbedUnimplementedCLIServiceServer() {}
func (UnimplementedCLIServiceServer) testEmbeddedByValue()                    {}

// UnsafeCLIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CLIServiceServer will
// result in compilation errors.
type UnsafeCLIServiceServer interface {
	mustEmbedUnimplementedCLIServiceServer()
}

func RegisterCLIServiceServer(s grpc.ServiceRegistrar, srv CLIServiceServer) {
	// If the following call panics, it indicates UnimplementedCLIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CLIService_ServiceDesc, srv)
}

func _CLIService_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CLIServiceServer).EventStream(&grpc.GenericServerStream[CLIRequest, CLIResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CLIService_EventStreamServer = grpc.BidiStreamingServer[CLIRequest, CLIResponse]

// CLIService_ServiceDesc is the grpc.ServiceDesc for CLIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CLIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hookwatch.cli.v1.CLIService",
	HandlerType: (*CLIServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _CLIService_EventStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cli/v1/cli.proto",
}
