// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: endpoint.proto

package cliv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EndpointRetryConfig represents retry settings for an endpoint.
type EndpointRetryConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxRetries    int32                  `protobuf:"varint,1,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Intervals     []int32                `protobuf:"varint,2,rep,packed,name=intervals,proto3" json:"intervals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointRetryConfig) Reset() {
	*x = EndpointRetryConfig{}
	mi := &file_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointRetryConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointRetryConfig) ProtoMessage() {}

func (x *EndpointRetryConfig) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointRetryConfig.ProtoReflect.Descriptor instead.
func (*EndpointRetryConfig) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *EndpointRetryConfig) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *EndpointRetryConfig) GetIntervals() []int32 {
	if x != nil {
		return x.Intervals
	}
	return nil
}

// EndpointSignatureConfig represents signature settings for an endpoint.
type EndpointSignatureConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InboundEnabled  bool                   `protobuf:"varint,1,opt,name=inbound_enabled,json=inboundEnabled,proto3" json:"inbound_enabled,omitempty"`
	InboundHeader   string                 `protobuf:"bytes,2,opt,name=inbound_header,json=inboundHeader,proto3" json:"inbound_header,omitempty"`
	InboundSecret   string                 `protobuf:"bytes,3,opt,name=inbound_secret,json=inboundSecret,proto3" json:"inbound_secret,omitempty"`
	OutboundEnabled bool                   `protobuf:"varint,4,opt,name=outbound_enabled,json=outboundEnabled,proto3" json:"outbound_enabled,omitempty"`
	OutboundSecret  string                 `protobuf:"bytes,5,opt,name=outbound_secret,json=outboundSecret,proto3" json:"outbound_secret,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EndpointSignatureConfig) Reset() {
	*x = EndpointSignatureConfig{}
	mi := &file_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointSignatureConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointSignatureConfig) ProtoMessage() {}

func (x *EndpointSignatureConfig) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointSignatureConfig.ProtoReflect.Descriptor instead.
func (*EndpointSignatureConfig) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointSignatureConfig) GetInboundEnabled() bool {
	if x != nil {
		return x.InboundEnabled
	}
	return false
}

func (x *EndpointSignatureConfig) GetInboundHeader() string {
	if x != nil {
		return x.InboundHeader
	}
	return ""
}

func (x *EndpointSignatureConfig) GetInboundSecret() string {
	if x != nil {
		return x.InboundSecret
	}
	return ""
}

func (x *EndpointSignatureConfig) GetOutboundEnabled() bool {
	if x != nil {
		return x.OutboundEnabled
	}
	return false
}

func (x *EndpointSignatureConfig) GetOutboundSecret() string {
	if x != nil {
		return x.OutboundSecret
	}
	return ""
}

// Endpoint represents a webhook endpoint.
type Endpoint struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Id              string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug            string                   `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Name            string                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DestinationUrl  string                   `protobuf:"bytes,4,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	IsActive        bool                     `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	RetryConfig     *EndpointRetryConfig     `protobuf:"bytes,6,opt,name=retry_config,json=retryConfig,proto3" json:"retry_config,omitempty"`
	SignatureConfig *EndpointSignatureConfig `protobuf:"bytes,7,opt,name=signature_config,json=signatureConfig,proto3" json:"signature_config,omitempty"`
	CreatedAt       *timestamppb.Timestamp   `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp   `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *Endpoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Endpoint) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Endpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Endpoint) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

func (x *Endpoint) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Endpoint) GetRetryConfig() *EndpointRetryConfig {
	if x != nil {
		return x.RetryConfig
	}
	return nil
}

func (x *Endpoint) GetSignatureConfig() *EndpointSignatureConfig {
	if x != nil {
		return x.SignatureConfig
	}
	return nil
}

func (x *Endpoint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Endpoint) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsRequest) Reset() {
	*x = ListEndpointsRequest{}
	mi := &file_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsRequest) ProtoMessage() {}

func (x *ListEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ListEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *ListEndpointsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ListEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*Endpoint            `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsResponse) Reset() {
	*x = ListEndpointsResponse{}
	mi := &file_endpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsResponse) ProtoMessage() {}

func (x *ListEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ListEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *ListEndpointsResponse) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type GetEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointRequest) Reset() {
	*x = GetEndpointRequest{}
	mi := &file_endpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointRequest) ProtoMessage() {}

func (x *GetEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointRequest.ProtoReflect.Descriptor instead.
func (*GetEndpointRequest) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *GetEndpointRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetEndpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *Endpoint              `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointResponse) Reset() {
	*x = GetEndpointResponse{}
	mi := &file_endpoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointResponse) ProtoMessage() {}

func (x *GetEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointResponse.ProtoReflect.Descriptor instead.
func (*GetEndpointResponse) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{6}
}

func (x *GetEndpointResponse) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type CreateEndpointRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApiKey         string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DestinationUrl string                 `protobuf:"bytes,3,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateEndpointRequest) Reset() {
	*x = CreateEndpointRequest{}
	mi := &file_endpoint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEndpointRequest) ProtoMessage() {}

func (x *CreateEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEndpointRequest.ProtoReflect.Descriptor instead.
func (*CreateEndpointRequest) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{7}
}

func (x *CreateEndpointRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEndpointRequest) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

type CreateEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *Endpoint              `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEndpointResponse) Reset() {
	*x = CreateEndpointResponse{}
	mi := &file_endpoint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEndpointResponse) ProtoMessage() {}

func (x *CreateEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEndpointResponse.ProtoReflect.Descriptor instead.
func (*CreateEndpointResponse) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{8}
}

func (x *CreateEndpointResponse) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type UpdateEndpointRequest struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	ApiKey          string                   `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id              string                   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DestinationUrl  string                   `protobuf:"bytes,4,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	IsActive        bool                     `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	RetryConfig     *EndpointRetryConfig     `protobuf:"bytes,6,opt,name=retry_config,json=retryConfig,proto3" json:"retry_config,omitempty"`
	SignatureConfig *EndpointSignatureConfig `protobuf:"bytes,7,opt,name=signature_config,json=signatureConfig,proto3" json:"signature_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateEndpointRequest) Reset() {
	*x = UpdateEndpointRequest{}
	mi := &file_endpoint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEndpointRequest) ProtoMessage() {}

func (x *UpdateEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEndpointRequest.ProtoReflect.Descriptor instead.
func (*UpdateEndpointRequest) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateEndpointRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *UpdateEndpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEndpointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateEndpointRequest) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

func (x *UpdateEndpointRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateEndpointRequest) GetRetryConfig() *EndpointRetryConfig {
	if x != nil {
		return x.RetryConfig
	}
	return nil
}

func (x *UpdateEndpointRequest) GetSignatureConfig() *EndpointSignatureConfig {
	if x != nil {
		return x.SignatureConfig
	}
	return nil
}

type UpdateEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *Endpoint              `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEndpointResponse) Reset() {
	*x = UpdateEndpointResponse{}
	mi := &file_endpoint_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEndpointResponse) ProtoMessage() {}

func (x *UpdateEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEndpointResponse.ProtoReflect.Descriptor instead.
func (*UpdateEndpointResponse) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateEndpointResponse) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type DeleteEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEndpointRequest) Reset() {
	*x = DeleteEndpointRequest{}
	mi := &file_endpoint_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEndpointRequest) ProtoMessage() {}

func (x *DeleteEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEndpointRequest.ProtoReflect.Descriptor instead.
func (*DeleteEndpointRequest) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteEndpointRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DeleteEndpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEndpointResponse) Reset() {
	*x = DeleteEndpointResponse{}
	mi := &file_endpoint_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEndpointResponse) ProtoMessage() {}

func (x *DeleteEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEndpointResponse.ProtoReflect.Descriptor instead.
func (*DeleteEndpointResponse) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{12}
}

type RegenerateInboundSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateInboundSecretRequest) Reset() {
	*x = RegenerateInboundSecretRequest{}
	mi := &file_endpoint_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateInboundSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateInboundSecretRequest) ProtoMessage() {}

func (x *RegenerateInboundSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateInboundSecretRequest.ProtoReflect.Descriptor instead.
func (*RegenerateInboundSecretRequest) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{13}
}

func (x *RegenerateInboundSecretRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RegenerateInboundSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegenerateInboundSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *Endpoint              `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateInboundSecretResponse) Reset() {
	*x = RegenerateInboundSecretResponse{}
	mi := &file_endpoint_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateInboundSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateInboundSecretResponse) ProtoMessage() {}

func (x *RegenerateInboundSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateInboundSecretResponse.ProtoReflect.Descriptor instead.
func (*RegenerateInboundSecretResponse) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{14}
}

func (x *RegenerateInboundSecretResponse) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type RegenerateOutboundSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateOutboundSecretRequest) Reset() {
	*x = RegenerateOutboundSecretRequest{}
	mi := &file_endpoint_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateOutboundSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateOutboundSecretRequest) ProtoMessage() {}

func (x *RegenerateOutboundSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateOutboundSecretRequest.ProtoReflect.Descriptor instead.
func (*RegenerateOutboundSecretRequest) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{15}
}

func (x *RegenerateOutboundSecretRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RegenerateOutboundSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RegenerateOutboundSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *Endpoint              `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateOutboundSecretResponse) Reset() {
	*x = RegenerateOutboundSecretResponse{}
	mi := &file_endpoint_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateOutboundSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateOutboundSecretResponse) ProtoMessage() {}

func (x *RegenerateOutboundSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoint_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateOutboundSecretResponse.ProtoReflect.Descriptor instead.
func (*RegenerateOutboundSecretResponse) Descriptor() ([]byte, []int) {
	return file_endpoint_proto_rawDescGZIP(), []int{16}
}

func (x *RegenerateOutboundSecretResponse) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

var File_endpoint_proto protoreflect.FileDescriptor

const file_endpoint_proto_rawDesc = "" +
	"\n" +
	"\x0eendpoint.proto\x12\x10hookwatch.cli.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"T\n" +
	"\x13EndpointRetryConfig\x12\x1f\n" +
	"\vmax_retries\x18\x01 \x01(\x05R\n" +
	"maxRetries\x12\x1c\n" +
	"\tintervals\x18\x02 \x03(\x05R\tintervals\"\xe4\x01\n" +
	"\x17EndpointSignatureConfig\x12'\n" +
	"\x0finbound_enabled\x18\x01 \x01(\bR\x0einboundEnabled\x12%\n" +
	"\x0einbound_header\x18\x02 \x01(\tR\rinboundHeader\x12%\n" +
	"\x0einbound_secret\x18\x03 \x01(\tR\rinboundSecret\x12)\n" +
	"\x10outbound_enabled\x18\x04 \x01(\bR\x0foutboundEnabled\x12'\n" +
	"\x0foutbound_secret\x18\x05 \x01(\tR\x0eoutboundSecret\"\x9e\x03\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12'\n" +
	"\x0fdestination_url\x18\x04 \x01(\tR\x0edestinationUrl\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12H\n" +
	"\fretry_config\x18\x06 \x01(\v2%.hookwatch.cli.v1.EndpointRetryConfigR\vretryConfig\x12T\n" +
	"\x10signature_config\x18\a \x01(\v2).hookwatch.cli.v1.EndpointSignatureConfigR\x0fsignatureConfig\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"/\n" +
	"\x14ListEndpointsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"Q\n" +
	"\x15ListEndpointsResponse\x128\n" +
	"\tendpoints\x18\x01 \x03(\v2\x1a.hookwatch.cli.v1.EndpointR\tendpoints\"=\n" +
	"\x12GetEndpointRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"M\n" +
	"\x13GetEndpointResponse\x126\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1a.hookwatch.cli.v1.EndpointR\bendpoint\"m\n" +
	"\x15CreateEndpointRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fdestination_url\x18\x03 \x01(\tR\x0edestinationUrl\"P\n" +
	"\x16CreateEndpointResponse\x126\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1a.hookwatch.cli.v1.EndpointR\bendpoint\"\xba\x02\n" +
	"\x15UpdateEndpointRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12'\n" +
	"\x0fdestination_url\x18\x04 \x01(\tR\x0edestinationUrl\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12H\n" +
	"\fretry_config\x18\x06 \x01(\v2%.hookwatch.cli.v1.EndpointRetryConfigR\vretryConfig\x12T\n" +
	"\x10signature_config\x18\a \x01(\v2).hookwatch.cli.v1.EndpointSignatureConfigR\x0fsignatureConfig\"P\n" +
	"\x16UpdateEndpointResponse\x126\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1a.hookwatch.cli.v1.EndpointR\bendpoint\"@\n" +
	"\x15DeleteEndpointRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteEndpointResponse\"I\n" +
	"\x1eRegenerateInboundSecretRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"Y\n" +
	"\x1fRegenerateInboundSecretResponse\x126\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1a.hookwatch.cli.v1.EndpointR\bendpoint\"J\n" +
	"\x1fRegenerateOutboundSecretRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"Z\n" +
	" RegenerateOutboundSecretResponse\x126\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1a.hookwatch.cli.v1.EndpointR\bendpoint2\x82\x06\n" +
	"\x0fEndpointService\x12`\n" +
	"\rListEndpoints\x12&.hookwatch.cli.v1.ListEndpointsRequest\x1a'.hookwatch.cli.v1.ListEndpointsResponse\x12Z\n" +
	"\vGetEndpoint\x12$.hookwatch.cli.v1.GetEndpointRequest\x1a%.hookwatch.cli.v1.GetEndpointResponse\x12c\n" +
	"\x0eCreateEndpoint\x12'.hookwatch.cli.v1.CreateEndpointRequest\x1a(.hookwatch.cli.v1.CreateEndpointResponse\x12c\n" +
	"\x0eUpdateEndpoint\x12'.hookwatch.cli.v1.UpdateEndpointRequest\x1a(.hookwatch.cli.v1.UpdateEndpointResponse\x12c\n" +
	"\x0eDeleteEndpoint\x12'.hookwatch.cli.v1.DeleteEndpointRequest\x1a(.hookwatch.cli.v1.DeleteEndpointResponse\x12~\n" +
	"\x17RegenerateInboundSecret\x120.hookwatch.cli.v1.RegenerateInboundSecretRequest\x1a1.hookwatch.cli.v1.RegenerateInboundSecretResponse\x12\x81\x01\n" +
	"\x18RegenerateOutboundSecret\x121.hookwatch.cli.v1.RegenerateOutboundSecretRequest\x1a2.hookwatch.cli.v1.RegenerateOutboundSecretResponseB-Z+github.com/hookwatch-dev/proto/cli/v1;cliv1b\x06proto3"

var (
	file_endpoint_proto_rawDescOnce sync.Once
	file_endpoint_proto_rawDescData []byte
)

func file_endpoint_proto_rawDescGZIP() []byte {
	file_endpoint_proto_rawDescOnce.Do(func() {
		file_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoint_proto_rawDesc), len(file_endpoint_proto_rawDesc)))
	})
	return file_endpoint_proto_rawDescData
}

var file_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_endpoint_proto_goTypes = []any{
	(*EndpointRetryConfig)(nil),              // 0: hookwatch.cli.v1.EndpointRetryConfig
	(*EndpointSignatureConfig)(nil),          // 1: hookwatch.cli.v1.EndpointSignatureConfig
	(*Endpoint)(nil),                         // 2: hookwatch.cli.v1.Endpoint
	(*ListEndpointsRequest)(nil),             // 3: hookwatch.cli.v1.ListEndpointsRequest
	(*ListEndpointsResponse)(nil),            // 4: hookwatch.cli.v1.ListEndpointsResponse
	(*GetEndpointRequest)(nil),               // 5: hookwatch.cli.v1.GetEndpointRequest
	(*GetEndpointResponse)(nil),              // 6: hookwatch.cli.v1.GetEndpointResponse
	(*CreateEndpointRequest)(nil),            // 7: hookwatch.cli.v1.CreateEndpointRequest
	(*CreateEndpointResponse)(nil),           // 8: hookwatch.cli.v1.CreateEndpointResponse
	(*UpdateEndpointRequest)(nil),            // 9: hookwatch.cli.v1.UpdateEndpointRequest
	(*UpdateEndpointResponse)(nil),           // 10: hookwatch.cli.v1.UpdateEndpointResponse
	(*DeleteEndpointRequest)(nil),            // 11: hookwatch.cli.v1.DeleteEndpointRequest
	(*DeleteEndpointResponse)(nil),           // 12: hookwatch.cli.v1.DeleteEndpointResponse
	(*RegenerateInboundSecretRequest)(nil),   // 13: hookwatch.cli.v1.RegenerateInboundSecretRequest
	(*RegenerateInboundSecretResponse)(nil),  // 14: hookwatch.cli.v1.RegenerateInboundSecretResponse
	(*RegenerateOutboundSecretRequest)(nil),  // 15: hookwatch.cli.v1.RegenerateOutboundSecretRequest
	(*RegenerateOutboundSecretResponse)(nil), // 16: hookwatch.cli.v1.RegenerateOutboundSecretResponse
	(*timestamppb.Timestamp)(nil),            // 17: google.protobuf.Timestamp
}
var file_endpoint_proto_depIdxs = []int32{
	0,  // 0: hookwatch.cli.v1.Endpoint.retry_config:type_name -> hookwatch.cli.v1.EndpointRetryConfig
	1,  // 1: hookwatch.cli.v1.Endpoint.signature_config:type_name -> hookwatch.cli.v1.EndpointSignatureConfig
	17, // 2: hookwatch.cli.v1.Endpoint.created_at:type_name -> google.protobuf.Timestamp
	17, // 3: hookwatch.cli.v1.Endpoint.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: hookwatch.cli.v1.ListEndpointsResponse.endpoints:type_name -> hookwatch.cli.v1.Endpoint
	2,  // 5: hookwatch.cli.v1.GetEndpointResponse.endpoint:type_name -> hookwatch.cli.v1.Endpoint
	2,  // 6: hookwatch.cli.v1.CreateEndpointResponse.endpoint:type_name -> hookwatch.cli.v1.Endpoint
	0,  // 7: hookwatch.cli.v1.UpdateEndpointRequest.retry_config:type_name -> hookwatch.cli.v1.EndpointRetryConfig
	1,  // 8: hookwatch.cli.v1.UpdateEndpointRequest.signature_config:type_name -> hookwatch.cli.v1.EndpointSignatureConfig
	2,  // 9: hookwatch.cli.v1.UpdateEndpointResponse.endpoint:type_name -> hookwatch.cli.v1.Endpoint
	2,  // 10: hookwatch.cli.v1.RegenerateInboundSecretResponse.endpoint:type_name -> hookwatch.cli.v1.Endpoint
	2,  // 11: hookwatch.cli.v1.RegenerateOutboundSecretResponse.endpoint:type_name -> hookwatch.cli.v1.Endpoint
	3,  // 12: hookwatch.cli.v1.EndpointService.ListEndpoints:input_type -> hookwatch.cli.v1.ListEndpointsRequest
	5,  // 13: hookwatch.cli.v1.EndpointService.GetEndpoint:input_type -> hookwatch.cli.v1.GetEndpointRequest
	7,  // 14: hookwatch.cli.v1.EndpointService.CreateEndpoint:input_type -> hookwatch.cli.v1.CreateEndpointRequest
	9,  // 15: hookwatch.cli.v1.EndpointService.UpdateEndpoint:input_type -> hookwatch.cli.v1.UpdateEndpointRequest
	11, // 16: hookwatch.cli.v1.EndpointService.DeleteEndpoint:input_type -> hookwatch.cli.v1.DeleteEndpointRequest
	13, // 17: hookwatch.cli.v1.EndpointService.RegenerateInboundSecret:input_type -> hookwatch.cli.v1.RegenerateInboundSecretRequest
	15, // 18: hookwatch.cli.v1.EndpointService.RegenerateOutboundSecret:input_type -> hookwatch.cli.v1.RegenerateOutboundSecretRequest
	4,  // 19: hookwatch.cli.v1.EndpointService.ListEndpoints:output_type -> hookwatch.cli.v1.ListEndpointsResponse
	6,  // 20: hookwatch.cli.v1.EndpointService.GetEndpoint:output_type -> hookwatch.cli.v1.GetEndpointResponse
	8,  // 21: hookwatch.cli.v1.EndpointService.CreateEndpoint:output_type -> hookwatch.cli.v1.CreateEndpointResponse
	10, // 22: hookwatch.cli.v1.EndpointService.UpdateEndpoint:output_type -> hookwatch.cli.v1.UpdateEndpointResponse
	12, // 23: hookwatch.cli.v1.EndpointService.DeleteEndpoint:output_type -> hookwatch.cli.v1.DeleteEndpointResponse
	14, // 24: hookwatch.cli.v1.EndpointService.RegenerateInboundSecret:output_type -> hookwatch.cli.v1.RegenerateInboundSecretResponse
	16, // 25: hookwatch.cli.v1.EndpointService.RegenerateOutboundSecret:output_type -> hookwatch.cli.v1.RegenerateOutboundSecretResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_endpoint_proto_init() }
func file_endpoint_proto_init() {
	if File_endpoint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoint_proto_rawDesc), len(file_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_endpoint_proto_goTypes,
		DependencyIndexes: file_endpoint_proto_depIdxs,
		MessageInfos:      file_endpoint_proto_msgTypes,
	}.Build()
	File_endpoint_proto = out.File
	file_endpoint_proto_goTypes = nil
	file_endpoint_proto_depIdxs = nil
}
