// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: event.proto

package cliv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event represents a webhook event.
type Event struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EndpointId     string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Method         string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body           string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	SourceIp       string                 `protobuf:"bytes,6,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	DeliveryStatus string                 `protobuf:"bytes,7,opt,name=delivery_status,json=deliveryStatus,proto3" json:"delivery_status,omitempty"`
	StatusCode     int32                  `protobuf:"varint,8,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	HasStatusCode  bool                   `protobuf:"varint,9,opt,name=has_status_code,json=hasStatusCode,proto3" json:"has_status_code,omitempty"`
	ResponseBody   string                 `protobuf:"bytes,10,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	RetryCount     int32                  `protobuf:"varint,11,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	NextRetryAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=next_retry_at,json=nextRetryAt,proto3" json:"next_retry_at,omitempty"`
	DeliveredAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *Event) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Event) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Event) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Event) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *Event) GetDeliveryStatus() string {
	if x != nil {
		return x.DeliveryStatus
	}
	return ""
}

func (x *Event) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Event) GetHasStatusCode() bool {
	if x != nil {
		return x.HasStatusCode
	}
	return false
}

func (x *Event) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *Event) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Event) GetNextRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRetryAt
	}
	return nil
}

func (x *Event) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *Event) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Event) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// EventDailyMetrics represents metrics for a single day.
type EventDailyMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Delivered     int32                  `protobuf:"varint,3,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Failed        int32                  `protobuf:"varint,4,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDailyMetrics) Reset() {
	*x = EventDailyMetrics{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDailyMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDailyMetrics) ProtoMessage() {}

func (x *EventDailyMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDailyMetrics.ProtoReflect.Descriptor instead.
func (*EventDailyMetrics) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventDailyMetrics) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *EventDailyMetrics) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *EventDailyMetrics) GetDelivered() int32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

func (x *EventDailyMetrics) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

// EventMetrics represents aggregated event metrics.
type EventMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalEvents    int32                  `protobuf:"varint,1,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	DeliveredCount int32                  `protobuf:"varint,2,opt,name=delivered_count,json=deliveredCount,proto3" json:"delivered_count,omitempty"`
	FailedCount    int32                  `protobuf:"varint,3,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	PendingCount   int32                  `protobuf:"varint,4,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	RetryingCount  int32                  `protobuf:"varint,5,opt,name=retrying_count,json=retryingCount,proto3" json:"retrying_count,omitempty"`
	DailyBreakdown []*EventDailyMetrics   `protobuf:"bytes,6,rep,name=daily_breakdown,json=dailyBreakdown,proto3" json:"daily_breakdown,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventMetrics) Reset() {
	*x = EventMetrics{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMetrics) ProtoMessage() {}

func (x *EventMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMetrics.ProtoReflect.Descriptor instead.
func (*EventMetrics) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *EventMetrics) GetTotalEvents() int32 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *EventMetrics) GetDeliveredCount() int32 {
	if x != nil {
		return x.DeliveredCount
	}
	return 0
}

func (x *EventMetrics) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *EventMetrics) GetPendingCount() int32 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *EventMetrics) GetRetryingCount() int32 {
	if x != nil {
		return x.RetryingCount
	}
	return 0
}

func (x *EventMetrics) GetDailyBreakdown() []*EventDailyMetrics {
	if x != nil {
		return x.DailyBreakdown
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	EndpointId    string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	From          string                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	Search        string                 `protobuf:"bytes,9,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *ListEventsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ListEventsRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *ListEventsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListEventsRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ListEventsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ListEventsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEventsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListEventsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{4}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{6}
}

func (x *GetEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type RetryEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryEventRequest) Reset() {
	*x = RetryEventRequest{}
	mi := &file_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryEventRequest) ProtoMessage() {}

func (x *RetryEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryEventRequest.ProtoReflect.Descriptor instead.
func (*RetryEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{7}
}

func (x *RetryEventRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *RetryEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetryEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryEventResponse) Reset() {
	*x = RetryEventResponse{}
	mi := &file_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryEventResponse) ProtoMessage() {}

func (x *RetryEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryEventResponse.ProtoReflect.Descriptor instead.
func (*RetryEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{8}
}

type ReplayEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayEventRequest) Reset() {
	*x = ReplayEventRequest{}
	mi := &file_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayEventRequest) ProtoMessage() {}

func (x *ReplayEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayEventRequest.ProtoReflect.Descriptor instead.
func (*ReplayEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{9}
}

func (x *ReplayEventRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ReplayEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReplayEventRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ReplayEventRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ReplayEventRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type ReplayEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayEventResponse) Reset() {
	*x = ReplayEventResponse{}
	mi := &file_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayEventResponse) ProtoMessage() {}

func (x *ReplayEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayEventResponse.ProtoReflect.Descriptor instead.
func (*ReplayEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{10}
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteEventRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{12}
}

type GetEventMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	EndpointId    string                 `protobuf:"bytes,3,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventMetricsRequest) Reset() {
	*x = GetEventMetricsRequest{}
	mi := &file_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventMetricsRequest) ProtoMessage() {}

func (x *GetEventMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetEventMetricsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{13}
}

func (x *GetEventMetricsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *GetEventMetricsRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *GetEventMetricsRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type GetEventMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *EventMetrics          `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventMetricsResponse) Reset() {
	*x = GetEventMetricsResponse{}
	mi := &file_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventMetricsResponse) ProtoMessage() {}

func (x *GetEventMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetEventMetricsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{14}
}

func (x *GetEventMetricsResponse) GetMetrics() *EventMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type CountEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	EndpointId    string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountEventsRequest) Reset() {
	*x = CountEventsRequest{}
	mi := &file_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountEventsRequest) ProtoMessage() {}

func (x *CountEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountEventsRequest.ProtoReflect.Descriptor instead.
func (*CountEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{15}
}

func (x *CountEventsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CountEventsRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *CountEventsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CountEventsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CountEventsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type CountEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountEventsResponse) Reset() {
	*x = CountEventsResponse{}
	mi := &file_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountEventsResponse) ProtoMessage() {}

func (x *CountEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountEventsResponse.ProtoReflect.Descriptor instead.
func (*CountEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{16}
}

func (x *CountEventsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ExportEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	EndpointId    string                 `protobuf:"bytes,3,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	From          string                 `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportEventsRequest) Reset() {
	*x = ExportEventsRequest{}
	mi := &file_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportEventsRequest) ProtoMessage() {}

func (x *ExportEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportEventsRequest.ProtoReflect.Descriptor instead.
func (*ExportEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{17}
}

func (x *ExportEventsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ExportEventsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExportEventsRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *ExportEventsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExportEventsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ExportEventsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ExportEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportEventsResponse) Reset() {
	*x = ExportEventsResponse{}
	mi := &file_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportEventsResponse) ProtoMessage() {}

func (x *ExportEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportEventsResponse.ProtoReflect.Descriptor instead.
func (*ExportEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{18}
}

func (x *ExportEventsResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExportEventsResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x10hookwatch.cli.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x05\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12>\n" +
	"\aheaders\x18\x04 \x03(\v2$.hookwatch.cli.v1.Event.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x1b\n" +
	"\tsource_ip\x18\x06 \x01(\tR\bsourceIp\x12'\n" +
	"\x0fdelivery_status\x18\a \x01(\tR\x0edeliveryStatus\x12\x1f\n" +
	"\vstatus_code\x18\b \x01(\x05R\n" +
	"statusCode\x12&\n" +
	"\x0fhas_status_code\x18\t \x01(\bR\rhasStatusCode\x12#\n" +
	"\rresponse_body\x18\n" +
	" \x01(\tR\fresponseBody\x12\x1f\n" +
	"\vretry_count\x18\v \x01(\x05R\n" +
	"retryCount\x12>\n" +
	"\rnext_retry_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vnextRetryAt\x12=\n" +
	"\fdelivered_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x11EventDailyMetrics\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x1c\n" +
	"\tdelivered\x18\x03 \x01(\x05R\tdelivered\x12\x16\n" +
	"\x06failed\x18\x04 \x01(\x05R\x06failed\"\x97\x02\n" +
	"\fEventMetrics\x12!\n" +
	"\ftotal_events\x18\x01 \x01(\x05R\vtotalEvents\x12'\n" +
	"\x0fdelivered_count\x18\x02 \x01(\x05R\x0edeliveredCount\x12!\n" +
	"\ffailed_count\x18\x03 \x01(\x05R\vfailedCount\x12#\n" +
	"\rpending_count\x18\x04 \x01(\x05R\fpendingCount\x12%\n" +
	"\x0eretrying_count\x18\x05 \x01(\x05R\rretryingCount\x12L\n" +
	"\x0fdaily_breakdown\x18\x06 \x03(\v2#.hookwatch.cli.v1.EventDailyMetricsR\x0edailyBreakdown\"\xf0\x01\n" +
	"\x11ListEventsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04from\x18\x05 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\tR\x02to\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\b \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\t \x01(\tR\x06search\"E\n" +
	"\x12ListEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.hookwatch.cli.v1.EventR\x06events\":\n" +
	"\x0fGetEventRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"A\n" +
	"\x10GetEventResponse\x12-\n" +
	"\x05event\x18\x01 \x01(\v2\x17.hookwatch.cli.v1.EventR\x05event\"<\n" +
	"\x11RetryEventRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x14\n" +
	"\x12RetryEventResponse\"\xf2\x01\n" +
	"\x12ReplayEventRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12K\n" +
	"\aheaders\x18\x04 \x03(\v21.hookwatch.cli.v1.ReplayEventRequest.HeadersEntryR\aheaders\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x15\n" +
	"\x13ReplayEventResponse\"=\n" +
	"\x12DeleteEventRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteEventResponse\"f\n" +
	"\x16GetEventMetricsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\x12\x1f\n" +
	"\vendpoint_id\x18\x03 \x01(\tR\n" +
	"endpointId\"S\n" +
	"\x17GetEventMetricsResponse\x128\n" +
	"\ametrics\x18\x01 \x01(\v2\x1e.hookwatch.cli.v1.EventMetricsR\ametrics\"\x8a\x01\n" +
	"\x12CountEventsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\"+\n" +
	"\x13CountEventsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\xa3\x01\n" +
	"\x13ExportEventsRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1f\n" +
	"\vendpoint_id\x18\x03 \x01(\tR\n" +
	"endpointId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04from\x18\x05 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\tR\x02to\"M\n" +
	"\x14ExportEventsResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType2\xee\x05\n" +
	"\fEventService\x12W\n" +
	"\n" +
	"ListEvents\x12#.hookwatch.cli.v1.ListEventsRequest\x1a$.hookwatch.cli.v1.ListEventsResponse\x12Q\n" +
	"\bGetEvent\x12!.hookwatch.cli.v1.GetEventRequest\x1a\".hookwatch.cli.v1.GetEventResponse\x12W\n" +
	"\n" +
	"RetryEvent\x12#.hookwatch.cli.v1.RetryEventRequest\x1a$.hookwatch.cli.v1.RetryEventResponse\x12Z\n" +
	"\vReplayEvent\x12$.hookwatch.cli.v1.ReplayEventRequest\x1a%.hookwatch.cli.v1.ReplayEventResponse\x12Z\n" +
	"\vDeleteEvent\x12$.hookwatch.cli.v1.DeleteEventRequest\x1a%.hookwatch.cli.v1.DeleteEventResponse\x12f\n" +
	"\x0fGetEventMetrics\x12(.hookwatch.cli.v1.GetEventMetricsRequest\x1a).hookwatch.cli.v1.GetEventMetricsResponse\x12Z\n" +
	"\vCountEvents\x12$.hookwatch.cli.v1.CountEventsRequest\x1a%.hookwatch.cli.v1.CountEventsResponse\x12]\n" +
	"\fExportEvents\x12%.hookwatch.cli.v1.ExportEventsRequest\x1a&.hookwatch.cli.v1.ExportEventsResponseB-Z+github.com/hookwatch-dev/proto/cli/v1;cliv1b\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_event_proto_goTypes = []any{
	(*Event)(nil),                   // 0: hookwatch.cli.v1.Event
	(*EventDailyMetrics)(nil),       // 1: hookwatch.cli.v1.EventDailyMetrics
	(*EventMetrics)(nil),            // 2: hookwatch.cli.v1.EventMetrics
	(*ListEventsRequest)(nil),       // 3: hookwatch.cli.v1.ListEventsRequest
	(*ListEventsResponse)(nil),      // 4: hookwatch.cli.v1.ListEventsResponse
	(*GetEventRequest)(nil),         // 5: hookwatch.cli.v1.GetEventRequest
	(*GetEventResponse)(nil),        // 6: hookwatch.cli.v1.GetEventResponse
	(*RetryEventRequest)(nil),       // 7: hookwatch.cli.v1.RetryEventRequest
	(*RetryEventResponse)(nil),      // 8: hookwatch.cli.v1.RetryEventResponse
	(*ReplayEventRequest)(nil),      // 9: hookwatch.cli.v1.ReplayEventRequest
	(*ReplayEventResponse)(nil),     // 10: hookwatch.cli.v1.ReplayEventResponse
	(*DeleteEventRequest)(nil),      // 11: hookwatch.cli.v1.DeleteEventRequest
	(*DeleteEventResponse)(nil),     // 12: hookwatch.cli.v1.DeleteEventResponse
	(*GetEventMetricsRequest)(nil),  // 13: hookwatch.cli.v1.GetEventMetricsRequest
	(*GetEventMetricsResponse)(nil), // 14: hookwatch.cli.v1.GetEventMetricsResponse
	(*CountEventsRequest)(nil),      // 15: hookwatch.cli.v1.CountEventsRequest
	(*CountEventsResponse)(nil),     // 16: hookwatch.cli.v1.CountEventsResponse
	(*ExportEventsRequest)(nil),     // 17: hookwatch.cli.v1.ExportEventsRequest
	(*ExportEventsResponse)(nil),    // 18: hookwatch.cli.v1.ExportEventsResponse
	nil,                             // 19: hookwatch.cli.v1.Event.HeadersEntry
	nil,                             // 20: hookwatch.cli.v1.ReplayEventRequest.HeadersEntry
	(*timestamppb.Timestamp)(nil),   // 21: google.protobuf.Timestamp
}
var file_event_proto_depIdxs = []int32{
	19, // 0: hookwatch.cli.v1.Event.headers:type_name -> hookwatch.cli.v1.Event.HeadersEntry
	21, // 1: hookwatch.cli.v1.Event.next_retry_at:type_name -> google.protobuf.Timestamp
	21, // 2: hookwatch.cli.v1.Event.delivered_at:type_name -> google.protobuf.Timestamp
	21, // 3: hookwatch.cli.v1.Event.created_at:type_name -> google.protobuf.Timestamp
	21, // 4: hookwatch.cli.v1.Event.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: hookwatch.cli.v1.EventMetrics.daily_breakdown:type_name -> hookwatch.cli.v1.EventDailyMetrics
	0,  // 6: hookwatch.cli.v1.ListEventsResponse.events:type_name -> hookwatch.cli.v1.Event
	0,  // 7: hookwatch.cli.v1.GetEventResponse.event:type_name -> hookwatch.cli.v1.Event
	20, // 8: hookwatch.cli.v1.ReplayEventRequest.headers:type_name -> hookwatch.cli.v1.ReplayEventRequest.HeadersEntry
	2,  // 9: hookwatch.cli.v1.GetEventMetricsResponse.metrics:type_name -> hookwatch.cli.v1.EventMetrics
	3,  // 10: hookwatch.cli.v1.EventService.ListEvents:input_type -> hookwatch.cli.v1.ListEventsRequest
	5,  // 11: hookwatch.cli.v1.EventService.GetEvent:input_type -> hookwatch.cli.v1.GetEventRequest
	7,  // 12: hookwatch.cli.v1.EventService.RetryEvent:input_type -> hookwatch.cli.v1.RetryEventRequest
	9,  // 13: hookwatch.cli.v1.EventService.ReplayEvent:input_type -> hookwatch.cli.v1.ReplayEventRequest
	11, // 14: hookwatch.cli.v1.EventService.DeleteEvent:input_type -> hookwatch.cli.v1.DeleteEventRequest
	13, // 15: hookwatch.cli.v1.EventService.GetEventMetrics:input_type -> hookwatch.cli.v1.GetEventMetricsRequest
	15, // 16: hookwatch.cli.v1.EventService.CountEvents:input_type -> hookwatch.cli.v1.CountEventsRequest
	17, // 17: hookwatch.cli.v1.EventService.ExportEvents:input_type -> hookwatch.cli.v1.ExportEventsRequest
	4,  // 18: hookwatch.cli.v1.EventService.ListEvents:output_type -> hookwatch.cli.v1.ListEventsResponse
	6,  // 19: hookwatch.cli.v1.EventService.GetEvent:output_type -> hookwatch.cli.v1.GetEventResponse
	8,  // 20: hookwatch.cli.v1.EventService.RetryEvent:output_type -> hookwatch.cli.v1.RetryEventResponse
	10, // 21: hookwatch.cli.v1.EventService.ReplayEvent:output_type -> hookwatch.cli.v1.ReplayEventResponse
	12, // 22: hookwatch.cli.v1.EventService.DeleteEvent:output_type -> hookwatch.cli.v1.DeleteEventResponse
	14, // 23: hookwatch.cli.v1.EventService.GetEventMetrics:output_type -> hookwatch.cli.v1.GetEventMetricsResponse
	16, // 24: hookwatch.cli.v1.EventService.CountEvents:output_type -> hookwatch.cli.v1.CountEventsResponse
	18, // 25: hookwatch.cli.v1.EventService.ExportEvents:output_type -> hookwatch.cli.v1.ExportEventsResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
