// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: worker/v1/worker.proto

package workerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryReportService_ReportDeliveryResult_FullMethodName = "/hookwatch.worker.v1.DeliveryReportService/ReportDeliveryResult"
)

// DeliveryReportServiceClient is the client API for DeliveryReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeliveryReportService handles delivery result reporting from worker to core
type DeliveryReportServiceClient interface {
	// ReportDeliveryResult reports the result of a webhook delivery attempt
	ReportDeliveryResult(ctx context.Context, in *DeliveryResultRequest, opts ...grpc.CallOption) (*DeliveryResultResponse, error)
}

type deliveryReportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryReportServiceClient(cc grpc.ClientConnInterface) DeliveryReportServiceClient {
	return &deliveryReportServiceClient{cc}
}

func (c *deliveryReportServiceClient) ReportDeliveryResult(ctx context.Context, in *DeliveryResultRequest, opts ...grpc.CallOption) (*DeliveryResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryResultResponse)
	err := c.cc.Invoke(ctx, DeliveryReportService_ReportDeliveryResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryReportServiceServer is the server API for DeliveryReportService service.
// All implementations must embed UnimplementedDeliveryReportServiceServer
// for forward compatibility.
//
// DeliveryReportService handles delivery result reporting from worker to core
type DeliveryReportServiceServer interface {
	// ReportDeliveryResult reports the result of a webhook delivery attempt
	ReportDeliveryResult(context.Context, *DeliveryResultRequest) (*DeliveryResultResponse, error)
	mustEmbedUnimplementedDeliveryReportServiceServer()
}

// UnimplementedDeliveryReportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryReportServiceServer struct{}

func (UnimplementedDeliveryReportServiceServer) ReportDeliveryResult(context.Context, *DeliveryResultRequest) (*DeliveryResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDeliveryResult not implemented")
}
func (UnimplementedDeliveryReportServiceServer) mustEmbedUnimplementedDeliveryReportServiceServer() {}
func (UnimplementedDeliveryReportServiceServer) testEmbeddedByValue()                               {}

// UnsafeDeliveryReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryReportServiceServer will
// result in compilation errors.
type UnsafeDeliveryReportServiceServer interface {
	mustEmbedUnimplementedDeliveryReportServiceServer()
}

func RegisterDeliveryReportServiceServer(s grpc.ServiceRegistrar, srv DeliveryReportServiceServer) {
	// If the following call panics, it indicates UnimplementedDeliveryReportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryReportService_ServiceDesc, srv)
}

func _DeliveryReportService_ReportDeliveryResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryReportServiceServer).ReportDeliveryResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryReportService_ReportDeliveryResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryReportServiceServer).ReportDeliveryResult(ctx, req.(*DeliveryResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryReportService_ServiceDesc is the grpc.ServiceDesc for DeliveryReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hookwatch.worker.v1.DeliveryReportService",
	HandlerType: (*DeliveryReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportDeliveryResult",
			Handler:    _DeliveryReportService_ReportDeliveryResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker/v1/worker.proto",
}
